// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: lumera/erc20policy/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgSetRegistrationPolicy configures the IBC voucher ERC20 auto-registration
// policy. It allows governance to control which IBC denoms are automatically
// registered as ERC20 token pairs on first IBC receive.
type MsgSetRegistrationPolicy struct {
	// authority is the address that controls the policy (defaults to x/gov).
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// mode is the registration policy mode: "all", "allowlist", or "none".
	// If empty, the mode is not changed.
	Mode string `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`
	// add_denoms is a list of exact IBC denoms (e.g. "ibc/HASH...") to add to
	// the allowlist. Only meaningful when mode is "allowlist".
	AddDenoms []string `protobuf:"bytes,3,rep,name=add_denoms,json=addDenoms,proto3" json:"add_denoms,omitempty"`
	// remove_denoms is a list of exact IBC denoms to remove from the allowlist.
	RemoveDenoms []string `protobuf:"bytes,4,rep,name=remove_denoms,json=removeDenoms,proto3" json:"remove_denoms,omitempty"`
	// add_base_denoms is a list of base token denominations (e.g. "uatom",
	// "uosmo") to add to the base denom allowlist. Base denom matching is
	// channel-independent: approving "uatom" allows ATOM arriving via any
	// IBC channel or multi-hop path.
	AddBaseDenoms []string `protobuf:"bytes,5,rep,name=add_base_denoms,json=addBaseDenoms,proto3" json:"add_base_denoms,omitempty"`
	// remove_base_denoms is a list of base denominations to remove from the
	// base denom allowlist.
	RemoveBaseDenoms []string `protobuf:"bytes,6,rep,name=remove_base_denoms,json=removeBaseDenoms,proto3" json:"remove_base_denoms,omitempty"`
}

func (m *MsgSetRegistrationPolicy) Reset()         { *m = MsgSetRegistrationPolicy{} }
func (m *MsgSetRegistrationPolicy) String() string { return proto.CompactTextString(m) }
func (*MsgSetRegistrationPolicy) ProtoMessage()    {}
func (*MsgSetRegistrationPolicy) Descriptor() ([]byte, []int) {
	return fileDescriptor_61f6ae3f2cfed8d9, []int{0}
}
func (m *MsgSetRegistrationPolicy) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetRegistrationPolicy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetRegistrationPolicy.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetRegistrationPolicy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetRegistrationPolicy.Merge(m, src)
}
func (m *MsgSetRegistrationPolicy) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetRegistrationPolicy) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetRegistrationPolicy.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetRegistrationPolicy proto.InternalMessageInfo

func (m *MsgSetRegistrationPolicy) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgSetRegistrationPolicy) GetMode() string {
	if m != nil {
		return m.Mode
	}
	return ""
}

func (m *MsgSetRegistrationPolicy) GetAddDenoms() []string {
	if m != nil {
		return m.AddDenoms
	}
	return nil
}

func (m *MsgSetRegistrationPolicy) GetRemoveDenoms() []string {
	if m != nil {
		return m.RemoveDenoms
	}
	return nil
}

func (m *MsgSetRegistrationPolicy) GetAddBaseDenoms() []string {
	if m != nil {
		return m.AddBaseDenoms
	}
	return nil
}

func (m *MsgSetRegistrationPolicy) GetRemoveBaseDenoms() []string {
	if m != nil {
		return m.RemoveBaseDenoms
	}
	return nil
}

// MsgSetRegistrationPolicyResponse is the response type for
// MsgSetRegistrationPolicy.
type MsgSetRegistrationPolicyResponse struct {
}

func (m *MsgSetRegistrationPolicyResponse) Reset()         { *m = MsgSetRegistrationPolicyResponse{} }
func (m *MsgSetRegistrationPolicyResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSetRegistrationPolicyResponse) ProtoMessage()    {}
func (*MsgSetRegistrationPolicyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_61f6ae3f2cfed8d9, []int{1}
}
func (m *MsgSetRegistrationPolicyResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetRegistrationPolicyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetRegistrationPolicyResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetRegistrationPolicyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetRegistrationPolicyResponse.Merge(m, src)
}
func (m *MsgSetRegistrationPolicyResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetRegistrationPolicyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetRegistrationPolicyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetRegistrationPolicyResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgSetRegistrationPolicy)(nil), "lumera.erc20policy.MsgSetRegistrationPolicy")
	proto.RegisterType((*MsgSetRegistrationPolicyResponse)(nil), "lumera.erc20policy.MsgSetRegistrationPolicyResponse")
}

func init() { proto.RegisterFile("lumera/erc20policy/tx.proto", fileDescriptor_61f6ae3f2cfed8d9) }

var fileDescriptor_61f6ae3f2cfed8d9 = []byte{
	// 382 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xce, 0x29, 0xcd, 0x4d,
	0x2d, 0x4a, 0xd4, 0x4f, 0x2d, 0x4a, 0x36, 0x32, 0x28, 0xc8, 0xcf, 0xc9, 0x4c, 0xae, 0xd4, 0x2f,
	0xa9, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x82, 0x48, 0xea, 0x21, 0x49, 0x4a, 0x09,
	0x26, 0xe6, 0x66, 0xe6, 0xe5, 0xeb, 0x83, 0x49, 0x88, 0x32, 0x29, 0xf1, 0xe4, 0xfc, 0xe2, 0xdc,
	0xfc, 0x62, 0xfd, 0xdc, 0xe2, 0x74, 0xfd, 0x32, 0x43, 0x10, 0x05, 0x95, 0x90, 0x84, 0x48, 0xc4,
	0x83, 0x79, 0xfa, 0x10, 0x0e, 0x44, 0x4a, 0xe9, 0x00, 0x13, 0x97, 0x84, 0x6f, 0x71, 0x7a, 0x70,
	0x6a, 0x49, 0x50, 0x6a, 0x7a, 0x66, 0x71, 0x49, 0x51, 0x62, 0x49, 0x66, 0x7e, 0x5e, 0x00, 0xd8,
	0x0e, 0x21, 0x33, 0x2e, 0xce, 0xc4, 0xd2, 0x92, 0x8c, 0xfc, 0xa2, 0xcc, 0x92, 0x4a, 0x09, 0x46,
	0x05, 0x46, 0x0d, 0x4e, 0x27, 0x89, 0x4b, 0x5b, 0x74, 0x45, 0xa0, 0x26, 0x38, 0xa6, 0xa4, 0x14,
	0xa5, 0x16, 0x17, 0x07, 0x97, 0x14, 0x65, 0xe6, 0xa5, 0x07, 0x21, 0x94, 0x0a, 0x09, 0x71, 0xb1,
	0xe4, 0xe6, 0xa7, 0xa4, 0x4a, 0x30, 0x81, 0xb4, 0x04, 0x81, 0xd9, 0x42, 0xb2, 0x5c, 0x5c, 0x89,
	0x29, 0x29, 0xf1, 0x29, 0xa9, 0x79, 0xf9, 0xb9, 0xc5, 0x12, 0xcc, 0x0a, 0xcc, 0x1a, 0x9c, 0x41,
	0x9c, 0x89, 0x29, 0x29, 0x2e, 0x60, 0x01, 0x21, 0x65, 0x2e, 0xde, 0xa2, 0xd4, 0xdc, 0xfc, 0xb2,
	0x54, 0x98, 0x0a, 0x16, 0xb0, 0x0a, 0x1e, 0x88, 0x20, 0x54, 0x91, 0x1a, 0x17, 0x3f, 0xc8, 0x8c,
	0xa4, 0xc4, 0x62, 0xb8, 0x32, 0x56, 0xb0, 0x32, 0xde, 0xc4, 0x94, 0x14, 0xa7, 0xc4, 0x62, 0x98,
	0x3a, 0x1d, 0x2e, 0x21, 0xa8, 0x61, 0xc8, 0x4a, 0xd9, 0xc0, 0x4a, 0x05, 0x20, 0x32, 0x08, 0xd5,
	0x56, 0x76, 0x4d, 0xcf, 0x37, 0x68, 0x21, 0x5c, 0xdf, 0xf5, 0x7c, 0x83, 0x96, 0x36, 0x96, 0xd8,
	0xc0, 0x15, 0x4a, 0x4a, 0x4a, 0x5c, 0x0a, 0xb8, 0xe4, 0x82, 0x52, 0x8b, 0x0b, 0xf2, 0xf3, 0x8a,
	0x53, 0x8d, 0x3a, 0x19, 0xb9, 0x98, 0x7d, 0x8b, 0xd3, 0x85, 0xaa, 0xb9, 0x44, 0xb1, 0x07, 0xb5,
	0x8e, 0x1e, 0x66, 0x1c, 0xeb, 0xe1, 0x32, 0x56, 0xca, 0x84, 0x14, 0xd5, 0x30, 0x47, 0x48, 0xb1,
	0x36, 0x3c, 0xdf, 0xa0, 0xc5, 0xe8, 0xa4, 0x7b, 0xe2, 0x91, 0x1c, 0xe3, 0x85, 0x47, 0x72, 0x8c,
	0x0f, 0x1e, 0xc9, 0x31, 0x4e, 0x78, 0x2c, 0xc7, 0x70, 0xe1, 0xb1, 0x1c, 0xc3, 0x8d, 0xc7, 0x72,
	0x0c, 0x51, 0xc2, 0x15, 0xa8, 0xe9, 0xaf, 0xb2, 0x20, 0xb5, 0x38, 0x89, 0x0d, 0x9c, 0x50, 0x8c,
	0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x74, 0x32, 0x19, 0x7e, 0xa2, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// SetRegistrationPolicy sets the IBC voucher ERC20 auto-registration policy.
	// Only the governance module account (x/gov authority) may call this.
	SetRegistrationPolicy(ctx context.Context, in *MsgSetRegistrationPolicy, opts ...grpc.CallOption) (*MsgSetRegistrationPolicyResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) SetRegistrationPolicy(ctx context.Context, in *MsgSetRegistrationPolicy, opts ...grpc.CallOption) (*MsgSetRegistrationPolicyResponse, error) {
	out := new(MsgSetRegistrationPolicyResponse)
	err := c.cc.Invoke(ctx, "/lumera.erc20policy.Msg/SetRegistrationPolicy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// SetRegistrationPolicy sets the IBC voucher ERC20 auto-registration policy.
	// Only the governance module account (x/gov authority) may call this.
	SetRegistrationPolicy(context.Context, *MsgSetRegistrationPolicy) (*MsgSetRegistrationPolicyResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) SetRegistrationPolicy(ctx context.Context, req *MsgSetRegistrationPolicy) (*MsgSetRegistrationPolicyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetRegistrationPolicy not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_SetRegistrationPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSetRegistrationPolicy)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SetRegistrationPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lumera.erc20policy.Msg/SetRegistrationPolicy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SetRegistrationPolicy(ctx, req.(*MsgSetRegistrationPolicy))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "lumera.erc20policy.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetRegistrationPolicy",
			Handler:    _Msg_SetRegistrationPolicy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lumera/erc20policy/tx.proto",
}

func (m *MsgSetRegistrationPolicy) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetRegistrationPolicy) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetRegistrationPolicy) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RemoveBaseDenoms) > 0 {
		for iNdEx := len(m.RemoveBaseDenoms) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.RemoveBaseDenoms[iNdEx])
			copy(dAtA[i:], m.RemoveBaseDenoms[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.RemoveBaseDenoms[iNdEx])))
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.AddBaseDenoms) > 0 {
		for iNdEx := len(m.AddBaseDenoms) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.AddBaseDenoms[iNdEx])
			copy(dAtA[i:], m.AddBaseDenoms[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.AddBaseDenoms[iNdEx])))
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.RemoveDenoms) > 0 {
		for iNdEx := len(m.RemoveDenoms) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.RemoveDenoms[iNdEx])
			copy(dAtA[i:], m.RemoveDenoms[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.RemoveDenoms[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.AddDenoms) > 0 {
		for iNdEx := len(m.AddDenoms) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.AddDenoms[iNdEx])
			copy(dAtA[i:], m.AddDenoms[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.AddDenoms[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Mode) > 0 {
		i -= len(m.Mode)
		copy(dAtA[i:], m.Mode)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Mode)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSetRegistrationPolicyResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetRegistrationPolicyResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetRegistrationPolicyResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgSetRegistrationPolicy) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Mode)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.AddDenoms) > 0 {
		for _, s := range m.AddDenoms {
			l = len(s)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	if len(m.RemoveDenoms) > 0 {
		for _, s := range m.RemoveDenoms {
			l = len(s)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	if len(m.AddBaseDenoms) > 0 {
		for _, s := range m.AddBaseDenoms {
			l = len(s)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	if len(m.RemoveBaseDenoms) > 0 {
		for _, s := range m.RemoveBaseDenoms {
			l = len(s)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgSetRegistrationPolicyResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgSetRegistrationPolicy) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetRegistrationPolicy: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetRegistrationPolicy: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mode", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Mode = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AddDenoms", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AddDenoms = append(m.AddDenoms, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RemoveDenoms", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RemoveDenoms = append(m.RemoveDenoms, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AddBaseDenoms", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AddBaseDenoms = append(m.AddBaseDenoms, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RemoveBaseDenoms", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RemoveBaseDenoms = append(m.RemoveBaseDenoms, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSetRegistrationPolicyResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetRegistrationPolicyResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetRegistrationPolicyResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
