package types

// Event types for the supernode module
const (
	EventTypeSupernodeRegistered       = "supernode_registered"
	EventTypeSupernodeDeRegistered     = "supernode_deregistered"
	EventTypeSupernodeStarted          = "supernode_started"
	EventTypeSupernodeStopped          = "supernode_stopped"
	EventTypeSupernodeUpdated          = "supernode_updated"
	EventTypeMetricsReported           = "supernode_metrics_reported"
	EventTypeSupernodePostponed        = "supernode_postponed"
	EventTypeSupernodeRecovered        = "supernode_recovered"
	EventTypeSupernodeStorageFull      = "supernode_storage_full"
	EventTypeSupernodeStorageRecovered = "supernode_storage_recovered"
	EventTypeDistribution              = "reward_distribution"

	AttributeKeyValidatorAddress = "validator_address"
	AttributeKeyIPAddress        = "ip_address"
	AttributeKeyReason           = "reason"
	AttributeKeyOldAccount       = "old_account"
	AttributeKeyNewAccount       = "new_account"
	AttributeKeySupernodeAccount = "supernode_account"
	AttributeKeyOldP2PPort       = "old_p2p_port"
	AttributeKeyP2PPort          = "p2p_port"
	AttributeKeyReRegistered     = "re_registered"
	AttributeKeyOldState         = "old_state"
	AttributeKeyOldIPAddress     = "old_ip_address"
	AttributeKeyHeight           = "height"
	AttributeKeyFieldsUpdated    = "fields_updated"
	AttributeKeyCompliant        = "compliant"
	AttributeKeyIssues           = "issues"

	AttributeKeyRewardRecipient     = "reward_recipient"
	AttributeKeyRewardValidator     = "reward_validator"
	AttributeKeyRewardAmount        = "reward_amount"
	AttributeKeyRewardSmoothedBytes = "reward_smoothed_bytes"
	AttributeKeyRewardRawBytes      = "reward_raw_bytes"
	AttributeKeyRewardEligibleCount = "reward_eligible_count"
	AttributeKeyRewardTotalPayout   = "reward_total_payout"
	AttributeKeyRewardPoolBalance   = "reward_pool_balance"
	AttributeKeyRewardReason        = "reward_reason"
	AttributeKeyRewardSkipReason    = "reward_skip_reason"
)
