// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: lumera/audit/v1/audit.proto

package types

import (
	encoding_binary "encoding/binary"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type PortState int32

const (
	PortState_PORT_STATE_UNKNOWN PortState = 0
	PortState_PORT_STATE_OPEN    PortState = 1
	PortState_PORT_STATE_CLOSED  PortState = 2
)

var PortState_name = map[int32]string{
	0: "PORT_STATE_UNKNOWN",
	1: "PORT_STATE_OPEN",
	2: "PORT_STATE_CLOSED",
}

var PortState_value = map[string]int32{
	"PORT_STATE_UNKNOWN": 0,
	"PORT_STATE_OPEN":    1,
	"PORT_STATE_CLOSED":  2,
}

func (x PortState) String() string {
	return proto.EnumName(PortState_name, int32(x))
}

func (PortState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0613fff850c07858, []int{0}
}

type AuditSelfReport struct {
	CpuUsagePercent    float64     `protobuf:"fixed64,1,opt,name=cpu_usage_percent,json=cpuUsagePercent,proto3" json:"cpu_usage_percent,omitempty"`
	MemUsagePercent    float64     `protobuf:"fixed64,2,opt,name=mem_usage_percent,json=memUsagePercent,proto3" json:"mem_usage_percent,omitempty"`
	DiskUsagePercent   float64     `protobuf:"fixed64,3,opt,name=disk_usage_percent,json=diskUsagePercent,proto3" json:"disk_usage_percent,omitempty"`
	InboundPortStates  []PortState `protobuf:"varint,4,rep,packed,name=inbound_port_states,json=inboundPortStates,proto3,enum=lumera.audit.v1.PortState" json:"inbound_port_states,omitempty"`
	FailedActionsCount uint32      `protobuf:"varint,5,opt,name=failed_actions_count,json=failedActionsCount,proto3" json:"failed_actions_count,omitempty"`
}

func (m *AuditSelfReport) Reset()         { *m = AuditSelfReport{} }
func (m *AuditSelfReport) String() string { return proto.CompactTextString(m) }
func (*AuditSelfReport) ProtoMessage()    {}
func (*AuditSelfReport) Descriptor() ([]byte, []int) {
	return fileDescriptor_0613fff850c07858, []int{0}
}
func (m *AuditSelfReport) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AuditSelfReport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AuditSelfReport.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AuditSelfReport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuditSelfReport.Merge(m, src)
}
func (m *AuditSelfReport) XXX_Size() int {
	return m.Size()
}
func (m *AuditSelfReport) XXX_DiscardUnknown() {
	xxx_messageInfo_AuditSelfReport.DiscardUnknown(m)
}

var xxx_messageInfo_AuditSelfReport proto.InternalMessageInfo

func (m *AuditSelfReport) GetCpuUsagePercent() float64 {
	if m != nil {
		return m.CpuUsagePercent
	}
	return 0
}

func (m *AuditSelfReport) GetMemUsagePercent() float64 {
	if m != nil {
		return m.MemUsagePercent
	}
	return 0
}

func (m *AuditSelfReport) GetDiskUsagePercent() float64 {
	if m != nil {
		return m.DiskUsagePercent
	}
	return 0
}

func (m *AuditSelfReport) GetInboundPortStates() []PortState {
	if m != nil {
		return m.InboundPortStates
	}
	return nil
}

func (m *AuditSelfReport) GetFailedActionsCount() uint32 {
	if m != nil {
		return m.FailedActionsCount
	}
	return 0
}

type AuditPeerObservation struct {
	TargetSupernodeAccount string `protobuf:"bytes,1,opt,name=target_supernode_account,json=targetSupernodeAccount,proto3" json:"target_supernode_account,omitempty"`
	// port_states[i] refers to required_open_ports[i] for the window.
	PortStates []PortState `protobuf:"varint,2,rep,packed,name=port_states,json=portStates,proto3,enum=lumera.audit.v1.PortState" json:"port_states,omitempty"`
}

func (m *AuditPeerObservation) Reset()         { *m = AuditPeerObservation{} }
func (m *AuditPeerObservation) String() string { return proto.CompactTextString(m) }
func (*AuditPeerObservation) ProtoMessage()    {}
func (*AuditPeerObservation) Descriptor() ([]byte, []int) {
	return fileDescriptor_0613fff850c07858, []int{1}
}
func (m *AuditPeerObservation) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AuditPeerObservation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AuditPeerObservation.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AuditPeerObservation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuditPeerObservation.Merge(m, src)
}
func (m *AuditPeerObservation) XXX_Size() int {
	return m.Size()
}
func (m *AuditPeerObservation) XXX_DiscardUnknown() {
	xxx_messageInfo_AuditPeerObservation.DiscardUnknown(m)
}

var xxx_messageInfo_AuditPeerObservation proto.InternalMessageInfo

func (m *AuditPeerObservation) GetTargetSupernodeAccount() string {
	if m != nil {
		return m.TargetSupernodeAccount
	}
	return ""
}

func (m *AuditPeerObservation) GetPortStates() []PortState {
	if m != nil {
		return m.PortStates
	}
	return nil
}

type AuditReport struct {
	SupernodeAccount string                  `protobuf:"bytes,1,opt,name=supernode_account,json=supernodeAccount,proto3" json:"supernode_account,omitempty"`
	WindowId         uint64                  `protobuf:"varint,2,opt,name=window_id,json=windowId,proto3" json:"window_id,omitempty"`
	ReportHeight     int64                   `protobuf:"varint,3,opt,name=report_height,json=reportHeight,proto3" json:"report_height,omitempty"`
	SelfReport       AuditSelfReport         `protobuf:"bytes,4,opt,name=self_report,json=selfReport,proto3" json:"self_report"`
	PeerObservations []*AuditPeerObservation `protobuf:"bytes,5,rep,name=peer_observations,json=peerObservations,proto3" json:"peer_observations,omitempty"`
}

func (m *AuditReport) Reset()         { *m = AuditReport{} }
func (m *AuditReport) String() string { return proto.CompactTextString(m) }
func (*AuditReport) ProtoMessage()    {}
func (*AuditReport) Descriptor() ([]byte, []int) {
	return fileDescriptor_0613fff850c07858, []int{2}
}
func (m *AuditReport) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AuditReport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AuditReport.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AuditReport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuditReport.Merge(m, src)
}
func (m *AuditReport) XXX_Size() int {
	return m.Size()
}
func (m *AuditReport) XXX_DiscardUnknown() {
	xxx_messageInfo_AuditReport.DiscardUnknown(m)
}

var xxx_messageInfo_AuditReport proto.InternalMessageInfo

func (m *AuditReport) GetSupernodeAccount() string {
	if m != nil {
		return m.SupernodeAccount
	}
	return ""
}

func (m *AuditReport) GetWindowId() uint64 {
	if m != nil {
		return m.WindowId
	}
	return 0
}

func (m *AuditReport) GetReportHeight() int64 {
	if m != nil {
		return m.ReportHeight
	}
	return 0
}

func (m *AuditReport) GetSelfReport() AuditSelfReport {
	if m != nil {
		return m.SelfReport
	}
	return AuditSelfReport{}
}

func (m *AuditReport) GetPeerObservations() []*AuditPeerObservation {
	if m != nil {
		return m.PeerObservations
	}
	return nil
}

// ProberTargets captures the deterministic prober -> targets mapping for a window.
type ProberTargets struct {
	ProberSupernodeAccount  string   `protobuf:"bytes,1,opt,name=prober_supernode_account,json=proberSupernodeAccount,proto3" json:"prober_supernode_account,omitempty"`
	TargetSupernodeAccounts []string `protobuf:"bytes,2,rep,name=target_supernode_accounts,json=targetSupernodeAccounts,proto3" json:"target_supernode_accounts,omitempty"`
}

func (m *ProberTargets) Reset()         { *m = ProberTargets{} }
func (m *ProberTargets) String() string { return proto.CompactTextString(m) }
func (*ProberTargets) ProtoMessage()    {}
func (*ProberTargets) Descriptor() ([]byte, []int) {
	return fileDescriptor_0613fff850c07858, []int{3}
}
func (m *ProberTargets) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ProberTargets) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ProberTargets.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ProberTargets) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProberTargets.Merge(m, src)
}
func (m *ProberTargets) XXX_Size() int {
	return m.Size()
}
func (m *ProberTargets) XXX_DiscardUnknown() {
	xxx_messageInfo_ProberTargets.DiscardUnknown(m)
}

var xxx_messageInfo_ProberTargets proto.InternalMessageInfo

func (m *ProberTargets) GetProberSupernodeAccount() string {
	if m != nil {
		return m.ProberSupernodeAccount
	}
	return ""
}

func (m *ProberTargets) GetTargetSupernodeAccounts() []string {
	if m != nil {
		return m.TargetSupernodeAccounts
	}
	return nil
}

type WindowSnapshot struct {
	WindowId          uint64 `protobuf:"varint,1,opt,name=window_id,json=windowId,proto3" json:"window_id,omitempty"`
	WindowStartHeight int64  `protobuf:"varint,2,opt,name=window_start_height,json=windowStartHeight,proto3" json:"window_start_height,omitempty"`
	// assignments is the minimal per-window source-of-truth for prober -> targets mapping.
	Assignments []ProberTargets `protobuf:"bytes,3,rep,name=assignments,proto3" json:"assignments"`
}

func (m *WindowSnapshot) Reset()         { *m = WindowSnapshot{} }
func (m *WindowSnapshot) String() string { return proto.CompactTextString(m) }
func (*WindowSnapshot) ProtoMessage()    {}
func (*WindowSnapshot) Descriptor() ([]byte, []int) {
	return fileDescriptor_0613fff850c07858, []int{4}
}
func (m *WindowSnapshot) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *WindowSnapshot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_WindowSnapshot.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *WindowSnapshot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WindowSnapshot.Merge(m, src)
}
func (m *WindowSnapshot) XXX_Size() int {
	return m.Size()
}
func (m *WindowSnapshot) XXX_DiscardUnknown() {
	xxx_messageInfo_WindowSnapshot.DiscardUnknown(m)
}

var xxx_messageInfo_WindowSnapshot proto.InternalMessageInfo

func (m *WindowSnapshot) GetWindowId() uint64 {
	if m != nil {
		return m.WindowId
	}
	return 0
}

func (m *WindowSnapshot) GetWindowStartHeight() int64 {
	if m != nil {
		return m.WindowStartHeight
	}
	return 0
}

func (m *WindowSnapshot) GetAssignments() []ProberTargets {
	if m != nil {
		return m.Assignments
	}
	return nil
}

func init() {
	proto.RegisterEnum("lumera.audit.v1.PortState", PortState_name, PortState_value)
	proto.RegisterType((*AuditSelfReport)(nil), "lumera.audit.v1.AuditSelfReport")
	proto.RegisterType((*AuditPeerObservation)(nil), "lumera.audit.v1.AuditPeerObservation")
	proto.RegisterType((*AuditReport)(nil), "lumera.audit.v1.AuditReport")
	proto.RegisterType((*ProberTargets)(nil), "lumera.audit.v1.ProberTargets")
	proto.RegisterType((*WindowSnapshot)(nil), "lumera.audit.v1.WindowSnapshot")
}

func init() { proto.RegisterFile("lumera/audit/v1/audit.proto", fileDescriptor_0613fff850c07858) }

var fileDescriptor_0613fff850c07858 = []byte{
	// 666 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0xcf, 0x4e, 0xdb, 0x4c,
	0x14, 0xc5, 0xe3, 0x24, 0x7c, 0xfa, 0xb8, 0x29, 0x24, 0x36, 0x14, 0x02, 0x48, 0x6e, 0x94, 0xaa,
	0x52, 0x84, 0xda, 0xa4, 0xd0, 0x65, 0x57, 0x81, 0xd2, 0xd2, 0x3f, 0x4a, 0x22, 0x3b, 0x08, 0xa9,
	0x9b, 0xd1, 0xc4, 0x1e, 0x8c, 0xd5, 0xd8, 0x63, 0xcd, 0x8c, 0xa1, 0x7d, 0x8b, 0x6e, 0xfa, 0x08,
	0xdd, 0x74, 0x5d, 0x75, 0xdb, 0x2d, 0x4b, 0xd4, 0x55, 0x57, 0x55, 0x05, 0x2f, 0x52, 0xcd, 0x8c,
	0x4b, 0x82, 0xa1, 0x42, 0x62, 0x13, 0xd9, 0xe7, 0x9c, 0x3b, 0xb9, 0x73, 0x7f, 0x57, 0x86, 0xb5,
	0x71, 0x1a, 0x11, 0x86, 0x3b, 0x38, 0xf5, 0x43, 0xd1, 0x39, 0xda, 0xd0, 0x0f, 0xed, 0x84, 0x51,
	0x41, 0xad, 0xaa, 0x36, 0xdb, 0x5a, 0x3b, 0xda, 0x58, 0x35, 0x71, 0x14, 0xc6, 0xb4, 0xa3, 0x7e,
	0x75, 0x66, 0x75, 0xc5, 0xa3, 0x3c, 0xa2, 0x1c, 0xa9, 0xb7, 0x8e, 0x7e, 0xc9, 0xac, 0xc5, 0x80,
	0x06, 0x54, 0xeb, 0xf2, 0x49, 0xab, 0xcd, 0x4f, 0x45, 0xa8, 0x76, 0xe5, 0x81, 0x2e, 0x19, 0x1f,
	0x38, 0x24, 0xa1, 0x4c, 0x58, 0xeb, 0x60, 0x7a, 0x49, 0x8a, 0x52, 0x8e, 0x03, 0x82, 0x12, 0xc2,
	0x3c, 0x12, 0x8b, 0xba, 0xd1, 0x30, 0x5a, 0x86, 0x53, 0xf5, 0x92, 0x74, 0x4f, 0xea, 0x03, 0x2d,
	0xcb, 0x6c, 0x44, 0xa2, 0x5c, 0xb6, 0xa8, 0xb3, 0x11, 0x89, 0x2e, 0x65, 0x1f, 0x82, 0xe5, 0x87,
	0xfc, 0x5d, 0x2e, 0x5c, 0x52, 0xe1, 0x9a, 0x74, 0x2e, 0xa5, 0x5f, 0xc1, 0x42, 0x18, 0x8f, 0x68,
	0x1a, 0xfb, 0x48, 0x76, 0x85, 0xb8, 0xc0, 0x82, 0xf0, 0x7a, 0xb9, 0x51, 0x6a, 0xcd, 0x6f, 0xae,
	0xb6, 0x73, 0xc3, 0x68, 0x0f, 0x28, 0x13, 0xae, 0x8c, 0x38, 0x66, 0x56, 0x76, 0xa1, 0x70, 0xeb,
	0x31, 0x2c, 0x1e, 0xe0, 0x70, 0x4c, 0x7c, 0x84, 0x3d, 0x11, 0xd2, 0x98, 0x23, 0x8f, 0xa6, 0xb1,
	0xa8, 0xcf, 0x34, 0x8c, 0xd6, 0x9c, 0x63, 0x69, 0xaf, 0xab, 0xad, 0x6d, 0xe9, 0x34, 0xbf, 0x18,
	0xb0, 0xa8, 0xe6, 0x32, 0x20, 0x84, 0xf5, 0x47, 0x9c, 0xb0, 0x23, 0x2c, 0x6d, 0x6b, 0x0f, 0xea,
	0x02, 0xb3, 0x80, 0x08, 0xc4, 0xd3, 0x84, 0xb0, 0x98, 0xfa, 0x04, 0x61, 0x4f, 0x1f, 0x27, 0x67,
	0x34, 0xbb, 0xb5, 0xf6, 0xe3, 0xeb, 0xa3, 0xe5, 0x6c, 0xf4, 0x5d, 0xcf, 0xeb, 0xfa, 0x3e, 0x23,
	0x9c, 0xbb, 0x82, 0x85, 0x71, 0xe0, 0x2c, 0xe9, 0x62, 0xf7, 0x6f, 0x6d, 0x57, 0x97, 0x5a, 0x4f,
	0xa1, 0x32, 0x7d, 0xcb, 0xe2, 0x8d, 0xb7, 0x84, 0xe4, 0xe2, 0x7a, 0xcd, 0x6f, 0x45, 0xa8, 0xa8,
	0x66, 0x33, 0x80, 0xbb, 0x60, 0xde, 0xaa, 0xb9, 0x1a, 0xcf, 0xb7, 0xb5, 0x06, 0xb3, 0xc7, 0x61,
	0xec, 0xd3, 0x63, 0x14, 0xfa, 0x0a, 0x6b, 0xd9, 0xf9, 0x5f, 0x0b, 0x2f, 0x7d, 0xeb, 0x3e, 0xcc,
	0x31, 0xf5, 0x87, 0xe8, 0x90, 0x84, 0xc1, 0xa1, 0x46, 0x59, 0x72, 0xee, 0x68, 0x71, 0x57, 0x69,
	0xd6, 0x0b, 0xa8, 0x70, 0x32, 0x3e, 0x40, 0x5a, 0xac, 0x97, 0x1b, 0x46, 0xab, 0xb2, 0xd9, 0xb8,
	0x72, 0xb1, 0xdc, 0x0e, 0x6e, 0x95, 0x4f, 0x7e, 0xdd, 0x2b, 0x38, 0xc0, 0x27, 0x5b, 0xe9, 0x80,
	0x99, 0x10, 0xc2, 0x10, 0x9d, 0xc0, 0xe0, 0xf5, 0x99, 0x46, 0xa9, 0x55, 0xd9, 0x7c, 0x70, 0xfd,
	0x71, 0x39, 0x74, 0x4e, 0x2d, 0xb9, 0x2c, 0xf0, 0xe6, 0x77, 0x03, 0xe6, 0x06, 0x8c, 0x8e, 0x08,
	0x1b, 0x2a, 0x2c, 0x5c, 0xe2, 0x4d, 0x94, 0x70, 0x4b, 0xbc, 0xba, 0xf8, 0x0a, 0xde, 0x7d, 0x58,
	0xf9, 0xd7, 0xd6, 0x68, 0xd8, 0x37, 0x9c, 0xbb, 0x7c, 0xfd, 0xda, 0xf0, 0xe6, 0x67, 0x03, 0xe6,
	0xf7, 0x15, 0x10, 0x37, 0xc6, 0x09, 0x3f, 0xa4, 0x39, 0x66, 0x46, 0x8e, 0x59, 0x1b, 0x16, 0x32,
	0x93, 0x0b, 0x3c, 0x21, 0x57, 0x54, 0xe4, 0x4c, 0x6d, 0xb9, 0xd2, 0xc9, 0xf0, 0x3d, 0x87, 0x0a,
	0xe6, 0x3c, 0x0c, 0xe2, 0x88, 0xc8, 0x56, 0x4b, 0x6a, 0xde, 0xf6, 0xd5, 0xbd, 0x9c, 0x1e, 0x62,
	0x06, 0x6f, 0xba, 0x70, 0xbd, 0x0f, 0xb3, 0x17, 0xbb, 0x6b, 0x2d, 0x81, 0x35, 0xe8, 0x3b, 0x43,
	0xe4, 0x0e, 0xbb, 0xc3, 0x1d, 0xb4, 0xd7, 0x7b, 0xdd, 0xeb, 0xef, 0xf7, 0x6a, 0x05, 0x6b, 0x01,
	0xaa, 0x53, 0x7a, 0x7f, 0xb0, 0xd3, 0xab, 0x19, 0xd6, 0x5d, 0x30, 0xa7, 0xc4, 0xed, 0x37, 0x7d,
	0x77, 0xe7, 0x59, 0xad, 0xb8, 0xb5, 0x7e, 0x72, 0x66, 0x1b, 0xa7, 0x67, 0xb6, 0xf1, 0xfb, 0xcc,
	0x36, 0x3e, 0x9e, 0xdb, 0x85, 0xd3, 0x73, 0xbb, 0xf0, 0xf3, 0xdc, 0x2e, 0xbc, 0xad, 0xbd, 0x9f,
	0x7c, 0x3f, 0xc5, 0x87, 0x84, 0xf0, 0xd1, 0x7f, 0xea, 0x5b, 0xf7, 0xe4, 0x4f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x83, 0x4b, 0x2e, 0xcc, 0x5f, 0x05, 0x00, 0x00,
}

func (m *AuditSelfReport) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AuditSelfReport) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AuditSelfReport) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.FailedActionsCount != 0 {
		i = encodeVarintAudit(dAtA, i, uint64(m.FailedActionsCount))
		i--
		dAtA[i] = 0x28
	}
	if len(m.InboundPortStates) > 0 {
		dAtA2 := make([]byte, len(m.InboundPortStates)*10)
		var j1 int
		for _, num := range m.InboundPortStates {
			for num >= 1<<7 {
				dAtA2[j1] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j1++
			}
			dAtA2[j1] = uint8(num)
			j1++
		}
		i -= j1
		copy(dAtA[i:], dAtA2[:j1])
		i = encodeVarintAudit(dAtA, i, uint64(j1))
		i--
		dAtA[i] = 0x22
	}
	if m.DiskUsagePercent != 0 {
		i -= 8
		encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(m.DiskUsagePercent))))
		i--
		dAtA[i] = 0x19
	}
	if m.MemUsagePercent != 0 {
		i -= 8
		encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(m.MemUsagePercent))))
		i--
		dAtA[i] = 0x11
	}
	if m.CpuUsagePercent != 0 {
		i -= 8
		encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(m.CpuUsagePercent))))
		i--
		dAtA[i] = 0x9
	}
	return len(dAtA) - i, nil
}

func (m *AuditPeerObservation) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AuditPeerObservation) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AuditPeerObservation) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PortStates) > 0 {
		dAtA4 := make([]byte, len(m.PortStates)*10)
		var j3 int
		for _, num := range m.PortStates {
			for num >= 1<<7 {
				dAtA4[j3] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j3++
			}
			dAtA4[j3] = uint8(num)
			j3++
		}
		i -= j3
		copy(dAtA[i:], dAtA4[:j3])
		i = encodeVarintAudit(dAtA, i, uint64(j3))
		i--
		dAtA[i] = 0x12
	}
	if len(m.TargetSupernodeAccount) > 0 {
		i -= len(m.TargetSupernodeAccount)
		copy(dAtA[i:], m.TargetSupernodeAccount)
		i = encodeVarintAudit(dAtA, i, uint64(len(m.TargetSupernodeAccount)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *AuditReport) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AuditReport) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AuditReport) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PeerObservations) > 0 {
		for iNdEx := len(m.PeerObservations) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PeerObservations[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintAudit(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	{
		size, err := m.SelfReport.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintAudit(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if m.ReportHeight != 0 {
		i = encodeVarintAudit(dAtA, i, uint64(m.ReportHeight))
		i--
		dAtA[i] = 0x18
	}
	if m.WindowId != 0 {
		i = encodeVarintAudit(dAtA, i, uint64(m.WindowId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.SupernodeAccount) > 0 {
		i -= len(m.SupernodeAccount)
		copy(dAtA[i:], m.SupernodeAccount)
		i = encodeVarintAudit(dAtA, i, uint64(len(m.SupernodeAccount)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ProberTargets) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ProberTargets) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ProberTargets) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.TargetSupernodeAccounts) > 0 {
		for iNdEx := len(m.TargetSupernodeAccounts) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.TargetSupernodeAccounts[iNdEx])
			copy(dAtA[i:], m.TargetSupernodeAccounts[iNdEx])
			i = encodeVarintAudit(dAtA, i, uint64(len(m.TargetSupernodeAccounts[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.ProberSupernodeAccount) > 0 {
		i -= len(m.ProberSupernodeAccount)
		copy(dAtA[i:], m.ProberSupernodeAccount)
		i = encodeVarintAudit(dAtA, i, uint64(len(m.ProberSupernodeAccount)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *WindowSnapshot) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *WindowSnapshot) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *WindowSnapshot) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Assignments) > 0 {
		for iNdEx := len(m.Assignments) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Assignments[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintAudit(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.WindowStartHeight != 0 {
		i = encodeVarintAudit(dAtA, i, uint64(m.WindowStartHeight))
		i--
		dAtA[i] = 0x10
	}
	if m.WindowId != 0 {
		i = encodeVarintAudit(dAtA, i, uint64(m.WindowId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintAudit(dAtA []byte, offset int, v uint64) int {
	offset -= sovAudit(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *AuditSelfReport) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CpuUsagePercent != 0 {
		n += 9
	}
	if m.MemUsagePercent != 0 {
		n += 9
	}
	if m.DiskUsagePercent != 0 {
		n += 9
	}
	if len(m.InboundPortStates) > 0 {
		l = 0
		for _, e := range m.InboundPortStates {
			l += sovAudit(uint64(e))
		}
		n += 1 + sovAudit(uint64(l)) + l
	}
	if m.FailedActionsCount != 0 {
		n += 1 + sovAudit(uint64(m.FailedActionsCount))
	}
	return n
}

func (m *AuditPeerObservation) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.TargetSupernodeAccount)
	if l > 0 {
		n += 1 + l + sovAudit(uint64(l))
	}
	if len(m.PortStates) > 0 {
		l = 0
		for _, e := range m.PortStates {
			l += sovAudit(uint64(e))
		}
		n += 1 + sovAudit(uint64(l)) + l
	}
	return n
}

func (m *AuditReport) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.SupernodeAccount)
	if l > 0 {
		n += 1 + l + sovAudit(uint64(l))
	}
	if m.WindowId != 0 {
		n += 1 + sovAudit(uint64(m.WindowId))
	}
	if m.ReportHeight != 0 {
		n += 1 + sovAudit(uint64(m.ReportHeight))
	}
	l = m.SelfReport.Size()
	n += 1 + l + sovAudit(uint64(l))
	if len(m.PeerObservations) > 0 {
		for _, e := range m.PeerObservations {
			l = e.Size()
			n += 1 + l + sovAudit(uint64(l))
		}
	}
	return n
}

func (m *ProberTargets) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ProberSupernodeAccount)
	if l > 0 {
		n += 1 + l + sovAudit(uint64(l))
	}
	if len(m.TargetSupernodeAccounts) > 0 {
		for _, s := range m.TargetSupernodeAccounts {
			l = len(s)
			n += 1 + l + sovAudit(uint64(l))
		}
	}
	return n
}

func (m *WindowSnapshot) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.WindowId != 0 {
		n += 1 + sovAudit(uint64(m.WindowId))
	}
	if m.WindowStartHeight != 0 {
		n += 1 + sovAudit(uint64(m.WindowStartHeight))
	}
	if len(m.Assignments) > 0 {
		for _, e := range m.Assignments {
			l = e.Size()
			n += 1 + l + sovAudit(uint64(l))
		}
	}
	return n
}

func sovAudit(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozAudit(x uint64) (n int) {
	return sovAudit(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *AuditSelfReport) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAudit
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AuditSelfReport: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AuditSelfReport: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field CpuUsagePercent", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			m.CpuUsagePercent = float64(math.Float64frombits(v))
		case 2:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field MemUsagePercent", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			m.MemUsagePercent = float64(math.Float64frombits(v))
		case 3:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field DiskUsagePercent", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			m.DiskUsagePercent = float64(math.Float64frombits(v))
		case 4:
			if wireType == 0 {
				var v PortState
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowAudit
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= PortState(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.InboundPortStates = append(m.InboundPortStates, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowAudit
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthAudit
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthAudit
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				if elementCount != 0 && len(m.InboundPortStates) == 0 {
					m.InboundPortStates = make([]PortState, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v PortState
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowAudit
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= PortState(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.InboundPortStates = append(m.InboundPortStates, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field InboundPortStates", wireType)
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FailedActionsCount", wireType)
			}
			m.FailedActionsCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAudit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FailedActionsCount |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipAudit(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAudit
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AuditPeerObservation) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAudit
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AuditPeerObservation: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AuditPeerObservation: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TargetSupernodeAccount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAudit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAudit
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAudit
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TargetSupernodeAccount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType == 0 {
				var v PortState
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowAudit
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= PortState(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.PortStates = append(m.PortStates, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowAudit
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthAudit
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthAudit
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				if elementCount != 0 && len(m.PortStates) == 0 {
					m.PortStates = make([]PortState, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v PortState
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowAudit
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= PortState(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.PortStates = append(m.PortStates, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field PortStates", wireType)
			}
		default:
			iNdEx = preIndex
			skippy, err := skipAudit(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAudit
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AuditReport) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAudit
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AuditReport: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AuditReport: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SupernodeAccount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAudit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAudit
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAudit
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SupernodeAccount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WindowId", wireType)
			}
			m.WindowId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAudit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.WindowId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReportHeight", wireType)
			}
			m.ReportHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAudit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ReportHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SelfReport", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAudit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAudit
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAudit
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.SelfReport.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PeerObservations", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAudit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAudit
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAudit
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PeerObservations = append(m.PeerObservations, &AuditPeerObservation{})
			if err := m.PeerObservations[len(m.PeerObservations)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAudit(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAudit
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ProberTargets) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAudit
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ProberTargets: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ProberTargets: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProberSupernodeAccount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAudit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAudit
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAudit
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProberSupernodeAccount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TargetSupernodeAccounts", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAudit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAudit
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAudit
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TargetSupernodeAccounts = append(m.TargetSupernodeAccounts, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAudit(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAudit
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *WindowSnapshot) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAudit
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: WindowSnapshot: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: WindowSnapshot: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WindowId", wireType)
			}
			m.WindowId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAudit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.WindowId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WindowStartHeight", wireType)
			}
			m.WindowStartHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAudit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.WindowStartHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Assignments", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAudit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAudit
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAudit
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Assignments = append(m.Assignments, ProberTargets{})
			if err := m.Assignments[len(m.Assignments)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAudit(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAudit
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipAudit(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowAudit
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAudit
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAudit
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthAudit
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupAudit
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthAudit
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthAudit        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowAudit          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupAudit = fmt.Errorf("proto: unexpected end of group")
)
