// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: lumera/audit/v1/evidence.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type EvidenceType int32

const (
	EvidenceType_EVIDENCE_TYPE_UNSPECIFIED EvidenceType = 0
	// action finalization rejected due to an invalid signature / signature-derived data.
	EvidenceType_EVIDENCE_TYPE_ACTION_FINALIZATION_SIGNATURE_FAILURE EvidenceType = 1
	// action finalization rejected because the attempted finalizer is not in the top-10 supernodes.
	EvidenceType_EVIDENCE_TYPE_ACTION_FINALIZATION_NOT_IN_TOP_10 EvidenceType = 2
	EvidenceType_EVIDENCE_TYPE_ACTION_EXPIRED                    EvidenceType = 3
	// storage challenge failure evidence submitted by the deterministic challenger.
	EvidenceType_EVIDENCE_TYPE_STORAGE_CHALLENGE_FAILURE EvidenceType = 4
	// client-observed cascade flow failure (upload/download).
	EvidenceType_EVIDENCE_TYPE_CASCADE_CLIENT_FAILURE EvidenceType = 5
)

var EvidenceType_name = map[int32]string{
	0: "EVIDENCE_TYPE_UNSPECIFIED",
	1: "EVIDENCE_TYPE_ACTION_FINALIZATION_SIGNATURE_FAILURE",
	2: "EVIDENCE_TYPE_ACTION_FINALIZATION_NOT_IN_TOP_10",
	3: "EVIDENCE_TYPE_ACTION_EXPIRED",
	4: "EVIDENCE_TYPE_STORAGE_CHALLENGE_FAILURE",
	5: "EVIDENCE_TYPE_CASCADE_CLIENT_FAILURE",
}

var EvidenceType_value = map[string]int32{
	"EVIDENCE_TYPE_UNSPECIFIED":                           0,
	"EVIDENCE_TYPE_ACTION_FINALIZATION_SIGNATURE_FAILURE": 1,
	"EVIDENCE_TYPE_ACTION_FINALIZATION_NOT_IN_TOP_10":     2,
	"EVIDENCE_TYPE_ACTION_EXPIRED":                        3,
	"EVIDENCE_TYPE_STORAGE_CHALLENGE_FAILURE":             4,
	"EVIDENCE_TYPE_CASCADE_CLIENT_FAILURE":                5,
}

func (x EvidenceType) String() string {
	return proto.EnumName(EvidenceType_name, int32(x))
}

func (EvidenceType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_449f638e48abdbaa, []int{0}
}

// Evidence is a stable outer record that stores evidence about an audited subject.
// Type-specific fields are encoded into the `metadata` bytes field.
type Evidence struct {
	// evidence_id is a chain-assigned unique identifier.
	EvidenceId uint64 `protobuf:"varint,1,opt,name=evidence_id,json=evidenceId,proto3" json:"evidence_id,omitempty"`
	// subject_address is the audited subject (e.g. supernode-related actor).
	SubjectAddress string `protobuf:"bytes,2,opt,name=subject_address,json=subjectAddress,proto3" json:"subject_address,omitempty"`
	// reporter_address is the submitter of the evidence.
	ReporterAddress string `protobuf:"bytes,3,opt,name=reporter_address,json=reporterAddress,proto3" json:"reporter_address,omitempty"`
	// action_id optionally links this evidence to a specific action.
	ActionId string `protobuf:"bytes,4,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	// evidence_type is a stable discriminator used to interpret metadata.
	EvidenceType EvidenceType `protobuf:"varint,5,opt,name=evidence_type,json=evidenceType,proto3,enum=lumera.audit.v1.EvidenceType" json:"evidence_type,omitempty"`
	// metadata is protobuf-binary bytes of a type-specific Evidence metadata message.
	Metadata []byte `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// reported_height is the block height when the evidence was submitted.
	ReportedHeight uint64 `protobuf:"varint,7,opt,name=reported_height,json=reportedHeight,proto3" json:"reported_height,omitempty"`
}

func (m *Evidence) Reset()         { *m = Evidence{} }
func (m *Evidence) String() string { return proto.CompactTextString(m) }
func (*Evidence) ProtoMessage()    {}
func (*Evidence) Descriptor() ([]byte, []int) {
	return fileDescriptor_449f638e48abdbaa, []int{0}
}
func (m *Evidence) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Evidence) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Evidence.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Evidence) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Evidence.Merge(m, src)
}
func (m *Evidence) XXX_Size() int {
	return m.Size()
}
func (m *Evidence) XXX_DiscardUnknown() {
	xxx_messageInfo_Evidence.DiscardUnknown(m)
}

var xxx_messageInfo_Evidence proto.InternalMessageInfo

func (m *Evidence) GetEvidenceId() uint64 {
	if m != nil {
		return m.EvidenceId
	}
	return 0
}

func (m *Evidence) GetSubjectAddress() string {
	if m != nil {
		return m.SubjectAddress
	}
	return ""
}

func (m *Evidence) GetReporterAddress() string {
	if m != nil {
		return m.ReporterAddress
	}
	return ""
}

func (m *Evidence) GetActionId() string {
	if m != nil {
		return m.ActionId
	}
	return ""
}

func (m *Evidence) GetEvidenceType() EvidenceType {
	if m != nil {
		return m.EvidenceType
	}
	return EvidenceType_EVIDENCE_TYPE_UNSPECIFIED
}

func (m *Evidence) GetMetadata() []byte {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Evidence) GetReportedHeight() uint64 {
	if m != nil {
		return m.ReportedHeight
	}
	return 0
}

func init() {
	proto.RegisterEnum("lumera.audit.v1.EvidenceType", EvidenceType_name, EvidenceType_value)
	proto.RegisterType((*Evidence)(nil), "lumera.audit.v1.Evidence")
}

func init() { proto.RegisterFile("lumera/audit/v1/evidence.proto", fileDescriptor_449f638e48abdbaa) }

var fileDescriptor_449f638e48abdbaa = []byte{
	// 467 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0xcf, 0x6e, 0xd3, 0x30,
	0x18, 0x6f, 0xba, 0x6e, 0x74, 0xa6, 0xb4, 0x91, 0xc5, 0x21, 0x1b, 0x2c, 0x44, 0x08, 0x69, 0xd1,
	0x10, 0x09, 0xa5, 0x07, 0xce, 0x6e, 0xea, 0x76, 0x96, 0xa2, 0xb4, 0x72, 0x52, 0x04, 0xbb, 0x58,
	0x59, 0x6d, 0x6d, 0x41, 0xb4, 0xa9, 0x12, 0xb7, 0x62, 0x6f, 0xc1, 0x81, 0x47, 0xe1, 0x21, 0x38,
	0x4e, 0x9c, 0xe0, 0x86, 0xda, 0x17, 0x41, 0x4d, 0x9a, 0x6e, 0x45, 0x93, 0x7a, 0xfc, 0xfd, 0xcd,
	0xe7, 0x2f, 0x1f, 0xd0, 0xbf, 0xcc, 0xc6, 0x22, 0x09, 0xed, 0x70, 0xc6, 0x23, 0x69, 0xcf, 0x9b,
	0xb6, 0x98, 0x47, 0x5c, 0x4c, 0x46, 0xc2, 0x9a, 0x26, 0xb1, 0x8c, 0x61, 0x23, 0xd7, 0xad, 0x4c,
	0xb7, 0xe6, 0xcd, 0xe3, 0xa3, 0x51, 0x9c, 0x8e, 0xe3, 0x94, 0x65, 0xb2, 0x9d, 0x83, 0xdc, 0xfb,
	0xf2, 0x4f, 0x19, 0x54, 0xf1, 0x3a, 0x0e, 0x5f, 0x80, 0xc7, 0x45, 0x15, 0x8b, 0xb8, 0xa6, 0x18,
	0x8a, 0x59, 0xa1, 0xa0, 0xa0, 0x08, 0x87, 0x08, 0x34, 0xd2, 0xd9, 0xe5, 0x67, 0x31, 0x92, 0x2c,
	0xe4, 0x3c, 0x11, 0x69, 0xaa, 0x95, 0x0d, 0xc5, 0x3c, 0x6c, 0x6b, 0xbf, 0x7e, 0xbc, 0x79, 0xba,
	0x2e, 0x46, 0xb9, 0xe2, 0xcb, 0x24, 0x9a, 0x5c, 0xd1, 0xfa, 0x3a, 0xb0, 0x66, 0xa1, 0x03, 0xd4,
	0x44, 0x4c, 0xe3, 0x44, 0x8a, 0x64, 0xd3, 0xb1, 0xb7, 0xa3, 0xa3, 0x51, 0x24, 0x8a, 0x92, 0x67,
	0xe0, 0x30, 0x1c, 0xc9, 0x28, 0x9e, 0xac, 0xc6, 0xac, 0xac, 0xd2, 0xb4, 0x9a, 0x13, 0x84, 0xc3,
	0x36, 0x78, 0xb2, 0x79, 0x85, 0xbc, 0x99, 0x0a, 0x6d, 0xdf, 0x50, 0xcc, 0xfa, 0xbb, 0x13, 0xeb,
	0xbf, 0xb5, 0x58, 0xc5, 0xbb, 0x83, 0x9b, 0xa9, 0xa0, 0x35, 0x71, 0x0f, 0xc1, 0x63, 0x50, 0x1d,
	0x0b, 0x19, 0xf2, 0x50, 0x86, 0xda, 0x81, 0xa1, 0x98, 0x35, 0xba, 0xc1, 0xf0, 0x14, 0x14, 0xf3,
	0x70, 0x76, 0x2d, 0xa2, 0xab, 0x6b, 0xa9, 0x3d, 0xca, 0x36, 0x55, 0x2f, 0xe8, 0xf3, 0x8c, 0x3d,
	0xfb, 0x5e, 0x06, 0xb5, 0xfb, 0xdf, 0x80, 0x27, 0xe0, 0x08, 0x7f, 0x20, 0x1d, 0xec, 0x39, 0x98,
	0x05, 0x9f, 0x06, 0x98, 0x0d, 0x3d, 0x7f, 0x80, 0x1d, 0xd2, 0x25, 0xb8, 0xa3, 0x96, 0xe0, 0x7b,
	0xd0, 0xda, 0x96, 0x91, 0x13, 0x90, 0xbe, 0xc7, 0xba, 0xc4, 0x43, 0x2e, 0xb9, 0x40, 0x19, 0xf0,
	0x49, 0xcf, 0x43, 0xc1, 0x90, 0x62, 0xd6, 0x45, 0xc4, 0x1d, 0x52, 0xac, 0x2a, 0xb0, 0x05, 0xec,
	0xdd, 0x41, 0xaf, 0x1f, 0x30, 0xe2, 0xb1, 0xa0, 0x3f, 0x60, 0xcd, 0xb7, 0x6a, 0x19, 0x1a, 0xe0,
	0xf9, 0x83, 0x21, 0xfc, 0x71, 0x40, 0x28, 0xee, 0xa8, 0x7b, 0xf0, 0x35, 0x38, 0xdd, 0x76, 0xf8,
	0x41, 0x9f, 0xa2, 0x1e, 0x66, 0xce, 0x39, 0x72, 0x5d, 0xec, 0xf5, 0xee, 0x66, 0xa8, 0x40, 0x13,
	0xbc, 0xda, 0x36, 0x3b, 0xc8, 0x77, 0x50, 0x07, 0x33, 0xc7, 0x25, 0xd8, 0x0b, 0x36, 0xce, 0xfd,
	0xf6, 0xd9, 0xcf, 0x85, 0xae, 0xdc, 0x2e, 0x74, 0xe5, 0xef, 0x42, 0x57, 0xbe, 0x2d, 0xf5, 0xd2,
	0xed, 0x52, 0x2f, 0xfd, 0x5e, 0xea, 0xa5, 0x0b, 0xf5, 0xeb, 0xdd, 0x4d, 0xaf, 0xfe, 0x5c, 0x7a,
	0x79, 0x90, 0x5d, 0x69, 0xeb, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb0, 0x48, 0x43, 0x20, 0xf3,
	0x02, 0x00, 0x00,
}

func (m *Evidence) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Evidence) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Evidence) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ReportedHeight != 0 {
		i = encodeVarintEvidence(dAtA, i, uint64(m.ReportedHeight))
		i--
		dAtA[i] = 0x38
	}
	if len(m.Metadata) > 0 {
		i -= len(m.Metadata)
		copy(dAtA[i:], m.Metadata)
		i = encodeVarintEvidence(dAtA, i, uint64(len(m.Metadata)))
		i--
		dAtA[i] = 0x32
	}
	if m.EvidenceType != 0 {
		i = encodeVarintEvidence(dAtA, i, uint64(m.EvidenceType))
		i--
		dAtA[i] = 0x28
	}
	if len(m.ActionId) > 0 {
		i -= len(m.ActionId)
		copy(dAtA[i:], m.ActionId)
		i = encodeVarintEvidence(dAtA, i, uint64(len(m.ActionId)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.ReporterAddress) > 0 {
		i -= len(m.ReporterAddress)
		copy(dAtA[i:], m.ReporterAddress)
		i = encodeVarintEvidence(dAtA, i, uint64(len(m.ReporterAddress)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.SubjectAddress) > 0 {
		i -= len(m.SubjectAddress)
		copy(dAtA[i:], m.SubjectAddress)
		i = encodeVarintEvidence(dAtA, i, uint64(len(m.SubjectAddress)))
		i--
		dAtA[i] = 0x12
	}
	if m.EvidenceId != 0 {
		i = encodeVarintEvidence(dAtA, i, uint64(m.EvidenceId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintEvidence(dAtA []byte, offset int, v uint64) int {
	offset -= sovEvidence(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Evidence) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.EvidenceId != 0 {
		n += 1 + sovEvidence(uint64(m.EvidenceId))
	}
	l = len(m.SubjectAddress)
	if l > 0 {
		n += 1 + l + sovEvidence(uint64(l))
	}
	l = len(m.ReporterAddress)
	if l > 0 {
		n += 1 + l + sovEvidence(uint64(l))
	}
	l = len(m.ActionId)
	if l > 0 {
		n += 1 + l + sovEvidence(uint64(l))
	}
	if m.EvidenceType != 0 {
		n += 1 + sovEvidence(uint64(m.EvidenceType))
	}
	l = len(m.Metadata)
	if l > 0 {
		n += 1 + l + sovEvidence(uint64(l))
	}
	if m.ReportedHeight != 0 {
		n += 1 + sovEvidence(uint64(m.ReportedHeight))
	}
	return n
}

func sovEvidence(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEvidence(x uint64) (n int) {
	return sovEvidence(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Evidence) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvidence
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Evidence: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Evidence: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EvidenceId", wireType)
			}
			m.EvidenceId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvidence
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EvidenceId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubjectAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvidence
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvidence
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvidence
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SubjectAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReporterAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvidence
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvidence
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvidence
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReporterAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActionId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvidence
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvidence
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvidence
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ActionId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EvidenceType", wireType)
			}
			m.EvidenceType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvidence
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EvidenceType |= EvidenceType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Metadata", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvidence
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthEvidence
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthEvidence
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Metadata = append(m.Metadata[:0], dAtA[iNdEx:postIndex]...)
			if m.Metadata == nil {
				m.Metadata = []byte{}
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReportedHeight", wireType)
			}
			m.ReportedHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvidence
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ReportedHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipEvidence(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvidence
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEvidence(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEvidence
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvidence
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvidence
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEvidence
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupEvidence
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthEvidence
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthEvidence        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEvidence          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupEvidence = fmt.Errorf("proto: unexpected end of group")
)
