// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: lumera/audit/v1/params.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the audit module.
type Params struct {
	ReportingWindowBlocks    uint64   `protobuf:"varint,1,opt,name=reporting_window_blocks,json=reportingWindowBlocks,proto3" json:"reporting_window_blocks,omitempty"`
	PeerQuorumReports        uint32   `protobuf:"varint,3,opt,name=peer_quorum_reports,json=peerQuorumReports,proto3" json:"peer_quorum_reports,omitempty"`
	MinProbeTargetsPerWindow uint32   `protobuf:"varint,4,opt,name=min_probe_targets_per_window,json=minProbeTargetsPerWindow,proto3" json:"min_probe_targets_per_window,omitempty"`
	MaxProbeTargetsPerWindow uint32   `protobuf:"varint,5,opt,name=max_probe_targets_per_window,json=maxProbeTargetsPerWindow,proto3" json:"max_probe_targets_per_window,omitempty"`
	RequiredOpenPorts        []uint32 `protobuf:"varint,6,rep,packed,name=required_open_ports,json=requiredOpenPorts,proto3" json:"required_open_ports,omitempty"`
	// Minimum required host free capacity (self reported).
	// free% = 100 - usage%
	// A usage% of 0 is treated as "unknown" (no action).
	MinCpuFreePercent  uint32 `protobuf:"varint,7,opt,name=min_cpu_free_percent,json=minCpuFreePercent,proto3" json:"min_cpu_free_percent,omitempty"`
	MinMemFreePercent  uint32 `protobuf:"varint,8,opt,name=min_mem_free_percent,json=minMemFreePercent,proto3" json:"min_mem_free_percent,omitempty"`
	MinDiskFreePercent uint32 `protobuf:"varint,9,opt,name=min_disk_free_percent,json=minDiskFreePercent,proto3" json:"min_disk_free_percent,omitempty"`
	// Number of consecutive windows a required port must be reported CLOSED by peers
	// at or above peer_port_postpone_threshold_percent before postponing the supernode.
	ConsecutiveWindowsToPostpone uint32 `protobuf:"varint,10,opt,name=consecutive_windows_to_postpone,json=consecutiveWindowsToPostpone,proto3" json:"consecutive_windows_to_postpone,omitempty"`
	// How many completed windows to keep in state for window-scoped data like WindowSnapshot,
	// AuditReport, and related indices. Pruning runs at window end.
	KeepLastWindowEntries uint64 `protobuf:"varint,11,opt,name=keep_last_window_entries,json=keepLastWindowEntries,proto3" json:"keep_last_window_entries,omitempty"`
	// Minimum percent (1-100) of peer reports that must report a required port as CLOSED
	// for the port to be treated as CLOSED for postponement purposes.
	//
	// 100 means unanimous.
	// Example: to approximate a 2/3 threshold, use 66 (since 2/3 ≈ 66.6%).
	PeerPortPostponeThresholdPercent uint32 `protobuf:"varint,12,opt,name=peer_port_postpone_threshold_percent,json=peerPortPostponeThresholdPercent,proto3" json:"peer_port_postpone_threshold_percent,omitempty"`
	// action_finalization_signature_failure_evidences_per_window is the per-window count threshold
	// for EVIDENCE_TYPE_ACTION_FINALIZATION_SIGNATURE_FAILURE.
	ActionFinalizationSignatureFailureEvidencesPerWindow uint32 `protobuf:"varint,13,opt,name=action_finalization_signature_failure_evidences_per_window,json=actionFinalizationSignatureFailureEvidencesPerWindow,proto3" json:"action_finalization_signature_failure_evidences_per_window,omitempty"`
	// action_finalization_signature_failure_consecutive_windows is the consecutive windows threshold
	// for EVIDENCE_TYPE_ACTION_FINALIZATION_SIGNATURE_FAILURE.
	ActionFinalizationSignatureFailureConsecutiveWindows uint32 `protobuf:"varint,14,opt,name=action_finalization_signature_failure_consecutive_windows,json=actionFinalizationSignatureFailureConsecutiveWindows,proto3" json:"action_finalization_signature_failure_consecutive_windows,omitempty"`
	// action_finalization_not_in_top10_evidences_per_window is the per-window count threshold
	// for EVIDENCE_TYPE_ACTION_FINALIZATION_NOT_IN_TOP_10.
	ActionFinalizationNotInTop10EvidencesPerWindow uint32 `protobuf:"varint,15,opt,name=action_finalization_not_in_top10_evidences_per_window,json=actionFinalizationNotInTop10EvidencesPerWindow,proto3" json:"action_finalization_not_in_top10_evidences_per_window,omitempty"`
	// action_finalization_not_in_top10_consecutive_windows is the consecutive windows threshold
	// for EVIDENCE_TYPE_ACTION_FINALIZATION_NOT_IN_TOP_10.
	ActionFinalizationNotInTop10ConsecutiveWindows uint32 `protobuf:"varint,16,opt,name=action_finalization_not_in_top10_consecutive_windows,json=actionFinalizationNotInTop10ConsecutiveWindows,proto3" json:"action_finalization_not_in_top10_consecutive_windows,omitempty"`
	// action_finalization_recovery_windows is the number of windows to wait before considering recovery.
	ActionFinalizationRecoveryWindows uint32 `protobuf:"varint,17,opt,name=action_finalization_recovery_windows,json=actionFinalizationRecoveryWindows,proto3" json:"action_finalization_recovery_windows,omitempty"`
	// action_finalization_recovery_max_total_bad_evidences is the maximum allowed total count of bad
	// action-finalization evidences in the recovery window for auto-recovery to occur.
	// Recovery happens ONLY IF total_bad < this value.
	ActionFinalizationRecoveryMaxTotalBadEvidences uint32 `protobuf:"varint,18,opt,name=action_finalization_recovery_max_total_bad_evidences,json=actionFinalizationRecoveryMaxTotalBadEvidences,proto3" json:"action_finalization_recovery_max_total_bad_evidences,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_3788ca0fc7eb9d86, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetReportingWindowBlocks() uint64 {
	if m != nil {
		return m.ReportingWindowBlocks
	}
	return 0
}

func (m *Params) GetPeerQuorumReports() uint32 {
	if m != nil {
		return m.PeerQuorumReports
	}
	return 0
}

func (m *Params) GetMinProbeTargetsPerWindow() uint32 {
	if m != nil {
		return m.MinProbeTargetsPerWindow
	}
	return 0
}

func (m *Params) GetMaxProbeTargetsPerWindow() uint32 {
	if m != nil {
		return m.MaxProbeTargetsPerWindow
	}
	return 0
}

func (m *Params) GetRequiredOpenPorts() []uint32 {
	if m != nil {
		return m.RequiredOpenPorts
	}
	return nil
}

func (m *Params) GetMinCpuFreePercent() uint32 {
	if m != nil {
		return m.MinCpuFreePercent
	}
	return 0
}

func (m *Params) GetMinMemFreePercent() uint32 {
	if m != nil {
		return m.MinMemFreePercent
	}
	return 0
}

func (m *Params) GetMinDiskFreePercent() uint32 {
	if m != nil {
		return m.MinDiskFreePercent
	}
	return 0
}

func (m *Params) GetConsecutiveWindowsToPostpone() uint32 {
	if m != nil {
		return m.ConsecutiveWindowsToPostpone
	}
	return 0
}

func (m *Params) GetKeepLastWindowEntries() uint64 {
	if m != nil {
		return m.KeepLastWindowEntries
	}
	return 0
}

func (m *Params) GetPeerPortPostponeThresholdPercent() uint32 {
	if m != nil {
		return m.PeerPortPostponeThresholdPercent
	}
	return 0
}

func (m *Params) GetActionFinalizationSignatureFailureEvidencesPerWindow() uint32 {
	if m != nil {
		return m.ActionFinalizationSignatureFailureEvidencesPerWindow
	}
	return 0
}

func (m *Params) GetActionFinalizationSignatureFailureConsecutiveWindows() uint32 {
	if m != nil {
		return m.ActionFinalizationSignatureFailureConsecutiveWindows
	}
	return 0
}

func (m *Params) GetActionFinalizationNotInTop10EvidencesPerWindow() uint32 {
	if m != nil {
		return m.ActionFinalizationNotInTop10EvidencesPerWindow
	}
	return 0
}

func (m *Params) GetActionFinalizationNotInTop10ConsecutiveWindows() uint32 {
	if m != nil {
		return m.ActionFinalizationNotInTop10ConsecutiveWindows
	}
	return 0
}

func (m *Params) GetActionFinalizationRecoveryWindows() uint32 {
	if m != nil {
		return m.ActionFinalizationRecoveryWindows
	}
	return 0
}

func (m *Params) GetActionFinalizationRecoveryMaxTotalBadEvidences() uint32 {
	if m != nil {
		return m.ActionFinalizationRecoveryMaxTotalBadEvidences
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "lumera.audit.v1.Params")
}

func init() { proto.RegisterFile("lumera/audit/v1/params.proto", fileDescriptor_3788ca0fc7eb9d86) }

var fileDescriptor_3788ca0fc7eb9d86 = []byte{
	// 644 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0x4f, 0x4f, 0x13, 0x41,
	0x18, 0xc6, 0xd9, 0x80, 0xa8, 0xa3, 0x08, 0x2c, 0x10, 0x37, 0x84, 0x94, 0x6a, 0x38, 0x10, 0x0f,
	0xad, 0x8d, 0xa8, 0x91, 0x83, 0x07, 0x10, 0x12, 0x13, 0x81, 0xb5, 0x36, 0x31, 0xf1, 0x32, 0x99,
	0xee, 0xbe, 0x94, 0x49, 0x77, 0xfe, 0x30, 0x33, 0x5b, 0x8a, 0x9f, 0xc2, 0xb3, 0x27, 0x3f, 0x8e,
	0x47, 0x8e, 0x1e, 0x0d, 0x5c, 0xfc, 0x18, 0x66, 0x66, 0xba, 0x4b, 0x09, 0x4b, 0xe0, 0xd2, 0x6e,
	0xfb, 0x3c, 0xbf, 0xf7, 0x79, 0xdf, 0x77, 0x36, 0x83, 0x56, 0xb2, 0x9c, 0x81, 0x22, 0x4d, 0x92,
	0xa7, 0xd4, 0x34, 0x07, 0xad, 0xa6, 0x24, 0x8a, 0x30, 0xdd, 0x90, 0x4a, 0x18, 0x11, 0xce, 0x7a,
	0xb5, 0xe1, 0xd4, 0xc6, 0xa0, 0xb5, 0x3c, 0x4f, 0x18, 0xe5, 0xa2, 0xe9, 0x3e, 0xbd, 0x67, 0x79,
	0xb1, 0x27, 0x7a, 0xc2, 0x3d, 0x36, 0xed, 0x93, 0xff, 0xf7, 0xf9, 0x4f, 0x84, 0xa6, 0x63, 0x57,
	0x2a, 0x7c, 0x83, 0x9e, 0x2a, 0x90, 0x42, 0x19, 0xca, 0x7b, 0xf8, 0x84, 0xf2, 0x54, 0x9c, 0xe0,
	0x6e, 0x26, 0x92, 0xbe, 0x8e, 0x82, 0x7a, 0xb0, 0x3e, 0xd5, 0x5e, 0x2a, 0xe5, 0xaf, 0x4e, 0xdd,
	0x72, 0x62, 0xd8, 0x40, 0x0b, 0x12, 0x40, 0xe1, 0xe3, 0x5c, 0xa8, 0x9c, 0x61, 0x6f, 0xd2, 0xd1,
	0x64, 0x3d, 0x58, 0x9f, 0x69, 0xcf, 0x5b, 0xe9, 0xb3, 0x53, 0xda, 0x5e, 0x08, 0xdf, 0xa3, 0x15,
	0x46, 0x39, 0x96, 0x4a, 0x74, 0x01, 0x1b, 0xa2, 0x7a, 0x60, 0x34, 0x96, 0xa0, 0x46, 0x99, 0xd1,
	0x94, 0x03, 0x23, 0x46, 0x79, 0x6c, 0x2d, 0x1d, 0xef, 0x88, 0x41, 0xf9, 0x54, 0xc7, 0x93, 0xe1,
	0xcd, 0xfc, 0xbd, 0x11, 0x4f, 0x86, 0xd5, 0x7c, 0x03, 0x2d, 0x28, 0x38, 0xce, 0xa9, 0x82, 0x14,
	0x0b, 0x09, 0x1c, 0xfb, 0x7e, 0xa7, 0xeb, 0x93, 0xb6, 0xdf, 0x42, 0x3a, 0x90, 0xc0, 0x63, 0xd7,
	0x6f, 0x13, 0x2d, 0xda, 0x7e, 0x13, 0x99, 0xe3, 0x43, 0x05, 0x60, 0xa3, 0x12, 0xe0, 0x26, 0xba,
	0xef, 0x07, 0x64, 0x94, 0x6f, 0xcb, 0x7c, 0x57, 0x01, 0xc4, 0x5e, 0x28, 0x00, 0x06, 0xec, 0x2a,
	0xf0, 0xa0, 0x04, 0xf6, 0x80, 0x8d, 0x03, 0x2d, 0xb4, 0x64, 0x81, 0x94, 0xea, 0xfe, 0x55, 0xe2,
	0xa1, 0x23, 0x42, 0x46, 0xf9, 0x07, 0xaa, 0xfb, 0xe3, 0xc8, 0x0e, 0x5a, 0x4d, 0x04, 0xd7, 0x90,
	0xe4, 0x86, 0x0e, 0x60, 0x34, 0xba, 0xc6, 0x46, 0x60, 0x29, 0xb4, 0x91, 0x82, 0x43, 0x84, 0x1c,
	0xbc, 0x32, 0x66, 0xf3, 0x0b, 0xd0, 0x1d, 0x11, 0x8f, 0x3c, 0xe1, 0x5b, 0x14, 0xf5, 0x01, 0x24,
	0xce, 0x88, 0x36, 0xc5, 0x99, 0x03, 0x37, 0x8a, 0x82, 0x8e, 0x1e, 0xf9, 0x43, 0xb7, 0xfa, 0x27,
	0xa2, 0x8d, 0x87, 0x77, 0xbc, 0x18, 0xee, 0xa3, 0x35, 0x77, 0xe8, 0x76, 0x77, 0x65, 0x24, 0x36,
	0x47, 0x0a, 0xf4, 0x91, 0xc8, 0xd2, 0x72, 0x82, 0xc7, 0xae, 0x89, 0xba, 0xf5, 0xda, 0x6d, 0x16,
	0xc1, 0x9d, 0xc2, 0x58, 0xcc, 0x33, 0x44, 0x9b, 0x24, 0x31, 0x54, 0x70, 0x7c, 0x48, 0x39, 0xc9,
	0xe8, 0x77, 0xe2, 0x7e, 0x68, 0xda, 0xe3, 0xc4, 0xe4, 0x0a, 0xf0, 0x21, 0xa1, 0x99, 0xfd, 0x86,
	0x01, 0x4d, 0x81, 0x27, 0x70, 0xe5, 0xc8, 0x67, 0x5c, 0xca, 0x86, 0xaf, 0xb0, 0x3b, 0x56, 0xe0,
	0x4b, 0xc1, 0xef, 0x7a, 0x7c, 0xa7, 0xa0, 0x2f, 0x5f, 0x87, 0x13, 0xf4, 0xee, 0x6e, 0xc9, 0x15,
	0xfb, 0x8e, 0x9e, 0xdc, 0x35, 0x78, 0xfb, 0xda, 0x29, 0x84, 0x0c, 0xbd, 0xae, 0x0a, 0xe6, 0xc2,
	0x60, 0xca, 0xb1, 0x11, 0xb2, 0xf5, 0xb2, 0x7a, 0xda, 0x59, 0x17, 0xda, 0xb8, 0x1e, 0xba, 0x2f,
	0xcc, 0x47, 0xde, 0xb1, 0x60, 0xc5, 0x9c, 0x19, 0xda, 0xb8, 0x35, 0xae, 0x6a, 0xc4, 0xb9, 0xdb,
	0xd3, 0x2a, 0x86, 0x3b, 0x40, 0x6b, 0x55, 0x69, 0x0a, 0x12, 0x31, 0x00, 0x75, 0x5a, 0x56, 0x9f,
	0x77, 0xd5, 0x9f, 0x5d, 0xaf, 0xde, 0x1e, 0x39, 0x8b, 0x82, 0x37, 0xb4, 0x5f, 0x16, 0xb4, 0x57,
	0x82, 0x11, 0x86, 0x64, 0xb8, 0x4b, 0xd2, 0xcb, 0xbd, 0x45, 0xe1, 0x4d, 0xed, 0x17, 0x01, 0x7b,
	0x64, 0xd8, 0xb1, 0xdc, 0x16, 0x49, 0xcb, 0xad, 0x6d, 0x4e, 0xfd, 0xfb, 0xb5, 0x1a, 0x6c, 0xbd,
	0xf8, 0x7d, 0x5e, 0x0b, 0xce, 0xce, 0x6b, 0xc1, 0xdf, 0xf3, 0x5a, 0xf0, 0xe3, 0xa2, 0x36, 0x71,
	0x76, 0x51, 0x9b, 0xf8, 0x73, 0x51, 0x9b, 0xf8, 0x36, 0x37, 0xbc, 0xbc, 0x89, 0xcd, 0xa9, 0x04,
	0xdd, 0x9d, 0x76, 0xf7, 0xe9, 0xab, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0x98, 0xb5, 0x04, 0xce,
	0xa9, 0x05, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.ReportingWindowBlocks != that1.ReportingWindowBlocks {
		return false
	}
	if this.PeerQuorumReports != that1.PeerQuorumReports {
		return false
	}
	if this.MinProbeTargetsPerWindow != that1.MinProbeTargetsPerWindow {
		return false
	}
	if this.MaxProbeTargetsPerWindow != that1.MaxProbeTargetsPerWindow {
		return false
	}
	if len(this.RequiredOpenPorts) != len(that1.RequiredOpenPorts) {
		return false
	}
	for i := range this.RequiredOpenPorts {
		if this.RequiredOpenPorts[i] != that1.RequiredOpenPorts[i] {
			return false
		}
	}
	if this.MinCpuFreePercent != that1.MinCpuFreePercent {
		return false
	}
	if this.MinMemFreePercent != that1.MinMemFreePercent {
		return false
	}
	if this.MinDiskFreePercent != that1.MinDiskFreePercent {
		return false
	}
	if this.ConsecutiveWindowsToPostpone != that1.ConsecutiveWindowsToPostpone {
		return false
	}
	if this.KeepLastWindowEntries != that1.KeepLastWindowEntries {
		return false
	}
	if this.PeerPortPostponeThresholdPercent != that1.PeerPortPostponeThresholdPercent {
		return false
	}
	if this.ActionFinalizationSignatureFailureEvidencesPerWindow != that1.ActionFinalizationSignatureFailureEvidencesPerWindow {
		return false
	}
	if this.ActionFinalizationSignatureFailureConsecutiveWindows != that1.ActionFinalizationSignatureFailureConsecutiveWindows {
		return false
	}
	if this.ActionFinalizationNotInTop10EvidencesPerWindow != that1.ActionFinalizationNotInTop10EvidencesPerWindow {
		return false
	}
	if this.ActionFinalizationNotInTop10ConsecutiveWindows != that1.ActionFinalizationNotInTop10ConsecutiveWindows {
		return false
	}
	if this.ActionFinalizationRecoveryWindows != that1.ActionFinalizationRecoveryWindows {
		return false
	}
	if this.ActionFinalizationRecoveryMaxTotalBadEvidences != that1.ActionFinalizationRecoveryMaxTotalBadEvidences {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ActionFinalizationRecoveryMaxTotalBadEvidences != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.ActionFinalizationRecoveryMaxTotalBadEvidences))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x90
	}
	if m.ActionFinalizationRecoveryWindows != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.ActionFinalizationRecoveryWindows))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x88
	}
	if m.ActionFinalizationNotInTop10ConsecutiveWindows != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.ActionFinalizationNotInTop10ConsecutiveWindows))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x80
	}
	if m.ActionFinalizationNotInTop10EvidencesPerWindow != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.ActionFinalizationNotInTop10EvidencesPerWindow))
		i--
		dAtA[i] = 0x78
	}
	if m.ActionFinalizationSignatureFailureConsecutiveWindows != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.ActionFinalizationSignatureFailureConsecutiveWindows))
		i--
		dAtA[i] = 0x70
	}
	if m.ActionFinalizationSignatureFailureEvidencesPerWindow != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.ActionFinalizationSignatureFailureEvidencesPerWindow))
		i--
		dAtA[i] = 0x68
	}
	if m.PeerPortPostponeThresholdPercent != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.PeerPortPostponeThresholdPercent))
		i--
		dAtA[i] = 0x60
	}
	if m.KeepLastWindowEntries != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.KeepLastWindowEntries))
		i--
		dAtA[i] = 0x58
	}
	if m.ConsecutiveWindowsToPostpone != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.ConsecutiveWindowsToPostpone))
		i--
		dAtA[i] = 0x50
	}
	if m.MinDiskFreePercent != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MinDiskFreePercent))
		i--
		dAtA[i] = 0x48
	}
	if m.MinMemFreePercent != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MinMemFreePercent))
		i--
		dAtA[i] = 0x40
	}
	if m.MinCpuFreePercent != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MinCpuFreePercent))
		i--
		dAtA[i] = 0x38
	}
	if len(m.RequiredOpenPorts) > 0 {
		dAtA2 := make([]byte, len(m.RequiredOpenPorts)*10)
		var j1 int
		for _, num := range m.RequiredOpenPorts {
			for num >= 1<<7 {
				dAtA2[j1] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j1++
			}
			dAtA2[j1] = uint8(num)
			j1++
		}
		i -= j1
		copy(dAtA[i:], dAtA2[:j1])
		i = encodeVarintParams(dAtA, i, uint64(j1))
		i--
		dAtA[i] = 0x32
	}
	if m.MaxProbeTargetsPerWindow != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxProbeTargetsPerWindow))
		i--
		dAtA[i] = 0x28
	}
	if m.MinProbeTargetsPerWindow != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MinProbeTargetsPerWindow))
		i--
		dAtA[i] = 0x20
	}
	if m.PeerQuorumReports != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.PeerQuorumReports))
		i--
		dAtA[i] = 0x18
	}
	if m.ReportingWindowBlocks != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.ReportingWindowBlocks))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ReportingWindowBlocks != 0 {
		n += 1 + sovParams(uint64(m.ReportingWindowBlocks))
	}
	if m.PeerQuorumReports != 0 {
		n += 1 + sovParams(uint64(m.PeerQuorumReports))
	}
	if m.MinProbeTargetsPerWindow != 0 {
		n += 1 + sovParams(uint64(m.MinProbeTargetsPerWindow))
	}
	if m.MaxProbeTargetsPerWindow != 0 {
		n += 1 + sovParams(uint64(m.MaxProbeTargetsPerWindow))
	}
	if len(m.RequiredOpenPorts) > 0 {
		l = 0
		for _, e := range m.RequiredOpenPorts {
			l += sovParams(uint64(e))
		}
		n += 1 + sovParams(uint64(l)) + l
	}
	if m.MinCpuFreePercent != 0 {
		n += 1 + sovParams(uint64(m.MinCpuFreePercent))
	}
	if m.MinMemFreePercent != 0 {
		n += 1 + sovParams(uint64(m.MinMemFreePercent))
	}
	if m.MinDiskFreePercent != 0 {
		n += 1 + sovParams(uint64(m.MinDiskFreePercent))
	}
	if m.ConsecutiveWindowsToPostpone != 0 {
		n += 1 + sovParams(uint64(m.ConsecutiveWindowsToPostpone))
	}
	if m.KeepLastWindowEntries != 0 {
		n += 1 + sovParams(uint64(m.KeepLastWindowEntries))
	}
	if m.PeerPortPostponeThresholdPercent != 0 {
		n += 1 + sovParams(uint64(m.PeerPortPostponeThresholdPercent))
	}
	if m.ActionFinalizationSignatureFailureEvidencesPerWindow != 0 {
		n += 1 + sovParams(uint64(m.ActionFinalizationSignatureFailureEvidencesPerWindow))
	}
	if m.ActionFinalizationSignatureFailureConsecutiveWindows != 0 {
		n += 1 + sovParams(uint64(m.ActionFinalizationSignatureFailureConsecutiveWindows))
	}
	if m.ActionFinalizationNotInTop10EvidencesPerWindow != 0 {
		n += 1 + sovParams(uint64(m.ActionFinalizationNotInTop10EvidencesPerWindow))
	}
	if m.ActionFinalizationNotInTop10ConsecutiveWindows != 0 {
		n += 2 + sovParams(uint64(m.ActionFinalizationNotInTop10ConsecutiveWindows))
	}
	if m.ActionFinalizationRecoveryWindows != 0 {
		n += 2 + sovParams(uint64(m.ActionFinalizationRecoveryWindows))
	}
	if m.ActionFinalizationRecoveryMaxTotalBadEvidences != 0 {
		n += 2 + sovParams(uint64(m.ActionFinalizationRecoveryMaxTotalBadEvidences))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReportingWindowBlocks", wireType)
			}
			m.ReportingWindowBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ReportingWindowBlocks |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PeerQuorumReports", wireType)
			}
			m.PeerQuorumReports = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PeerQuorumReports |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinProbeTargetsPerWindow", wireType)
			}
			m.MinProbeTargetsPerWindow = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinProbeTargetsPerWindow |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxProbeTargetsPerWindow", wireType)
			}
			m.MaxProbeTargetsPerWindow = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxProbeTargetsPerWindow |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType == 0 {
				var v uint32
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowParams
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint32(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.RequiredOpenPorts = append(m.RequiredOpenPorts, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowParams
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthParams
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthParams
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.RequiredOpenPorts) == 0 {
					m.RequiredOpenPorts = make([]uint32, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint32
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowParams
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint32(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.RequiredOpenPorts = append(m.RequiredOpenPorts, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field RequiredOpenPorts", wireType)
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinCpuFreePercent", wireType)
			}
			m.MinCpuFreePercent = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinCpuFreePercent |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinMemFreePercent", wireType)
			}
			m.MinMemFreePercent = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinMemFreePercent |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinDiskFreePercent", wireType)
			}
			m.MinDiskFreePercent = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinDiskFreePercent |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsecutiveWindowsToPostpone", wireType)
			}
			m.ConsecutiveWindowsToPostpone = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ConsecutiveWindowsToPostpone |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field KeepLastWindowEntries", wireType)
			}
			m.KeepLastWindowEntries = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.KeepLastWindowEntries |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PeerPortPostponeThresholdPercent", wireType)
			}
			m.PeerPortPostponeThresholdPercent = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PeerPortPostponeThresholdPercent |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActionFinalizationSignatureFailureEvidencesPerWindow", wireType)
			}
			m.ActionFinalizationSignatureFailureEvidencesPerWindow = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ActionFinalizationSignatureFailureEvidencesPerWindow |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActionFinalizationSignatureFailureConsecutiveWindows", wireType)
			}
			m.ActionFinalizationSignatureFailureConsecutiveWindows = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ActionFinalizationSignatureFailureConsecutiveWindows |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 15:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActionFinalizationNotInTop10EvidencesPerWindow", wireType)
			}
			m.ActionFinalizationNotInTop10EvidencesPerWindow = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ActionFinalizationNotInTop10EvidencesPerWindow |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 16:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActionFinalizationNotInTop10ConsecutiveWindows", wireType)
			}
			m.ActionFinalizationNotInTop10ConsecutiveWindows = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ActionFinalizationNotInTop10ConsecutiveWindows |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 17:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActionFinalizationRecoveryWindows", wireType)
			}
			m.ActionFinalizationRecoveryWindows = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ActionFinalizationRecoveryWindows |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 18:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActionFinalizationRecoveryMaxTotalBadEvidences", wireType)
			}
			m.ActionFinalizationRecoveryMaxTotalBadEvidences = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ActionFinalizationRecoveryMaxTotalBadEvidences |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
