// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: lumera/audit/v1/params.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the audit module.
type Params struct {
	EpochLengthBlocks uint64 `protobuf:"varint,1,opt,name=epoch_length_blocks,json=epochLengthBlocks,proto3" json:"epoch_length_blocks,omitempty"`
	// epoch_zero_height defines the reference chain height at which epoch_id = 0 starts.
	// This makes epoch boundaries deterministic from genesis without needing to query state.
	EpochZeroHeight         uint64   `protobuf:"varint,2,opt,name=epoch_zero_height,json=epochZeroHeight,proto3" json:"epoch_zero_height,omitempty"`
	PeerQuorumReports       uint32   `protobuf:"varint,3,opt,name=peer_quorum_reports,json=peerQuorumReports,proto3" json:"peer_quorum_reports,omitempty"`
	MinProbeTargetsPerEpoch uint32   `protobuf:"varint,4,opt,name=min_probe_targets_per_epoch,json=minProbeTargetsPerEpoch,proto3" json:"min_probe_targets_per_epoch,omitempty"`
	MaxProbeTargetsPerEpoch uint32   `protobuf:"varint,5,opt,name=max_probe_targets_per_epoch,json=maxProbeTargetsPerEpoch,proto3" json:"max_probe_targets_per_epoch,omitempty"`
	RequiredOpenPorts       []uint32 `protobuf:"varint,6,rep,packed,name=required_open_ports,json=requiredOpenPorts,proto3" json:"required_open_ports,omitempty"`
	// Minimum required host free capacity (self reported).
	// free% = 100 - usage%
	// A usage% of 0 is treated as "unknown" (no action).
	MinCpuFreePercent  uint32 `protobuf:"varint,7,opt,name=min_cpu_free_percent,json=minCpuFreePercent,proto3" json:"min_cpu_free_percent,omitempty"`
	MinMemFreePercent  uint32 `protobuf:"varint,8,opt,name=min_mem_free_percent,json=minMemFreePercent,proto3" json:"min_mem_free_percent,omitempty"`
	MinDiskFreePercent uint32 `protobuf:"varint,9,opt,name=min_disk_free_percent,json=minDiskFreePercent,proto3" json:"min_disk_free_percent,omitempty"`
	// Number of consecutive epochs a required port must be reported CLOSED by peers
	// at or above peer_port_postpone_threshold_percent before postponing the supernode.
	ConsecutiveEpochsToPostpone uint32 `protobuf:"varint,10,opt,name=consecutive_epochs_to_postpone,json=consecutiveEpochsToPostpone,proto3" json:"consecutive_epochs_to_postpone,omitempty"`
	// How many completed epochs to keep in state for epoch-scoped data like EpochReport
	// and related indices. Pruning runs at epoch end.
	KeepLastEpochEntries uint64 `protobuf:"varint,11,opt,name=keep_last_epoch_entries,json=keepLastEpochEntries,proto3" json:"keep_last_epoch_entries,omitempty"`
	// Minimum percent (1-100) of peer reports that must report a required port as CLOSED
	// for the port to be treated as CLOSED for postponement purposes.
	//
	// 100 means unanimous.
	// Example: to approximate a 2/3 threshold, use 66 (since 2/3 ≈ 66.6%).
	PeerPortPostponeThresholdPercent uint32 `protobuf:"varint,12,opt,name=peer_port_postpone_threshold_percent,json=peerPortPostponeThresholdPercent,proto3" json:"peer_port_postpone_threshold_percent,omitempty"`
	// action_finalization_signature_failure_evidences_per_epoch is the per-epoch count threshold
	// for EVIDENCE_TYPE_ACTION_FINALIZATION_SIGNATURE_FAILURE.
	ActionFinalizationSignatureFailureEvidencesPerEpoch uint32 `protobuf:"varint,13,opt,name=action_finalization_signature_failure_evidences_per_epoch,json=actionFinalizationSignatureFailureEvidencesPerEpoch,proto3" json:"action_finalization_signature_failure_evidences_per_epoch,omitempty"`
	// action_finalization_signature_failure_consecutive_epochs is the consecutive epochs threshold
	// for EVIDENCE_TYPE_ACTION_FINALIZATION_SIGNATURE_FAILURE.
	ActionFinalizationSignatureFailureConsecutiveEpochs uint32 `protobuf:"varint,14,opt,name=action_finalization_signature_failure_consecutive_epochs,json=actionFinalizationSignatureFailureConsecutiveEpochs,proto3" json:"action_finalization_signature_failure_consecutive_epochs,omitempty"`
	// action_finalization_not_in_top10_evidences_per_epoch is the per-epoch count threshold
	// for EVIDENCE_TYPE_ACTION_FINALIZATION_NOT_IN_TOP_10.
	ActionFinalizationNotInTop10EvidencesPerEpoch uint32 `protobuf:"varint,15,opt,name=action_finalization_not_in_top10_evidences_per_epoch,json=actionFinalizationNotInTop10EvidencesPerEpoch,proto3" json:"action_finalization_not_in_top10_evidences_per_epoch,omitempty"`
	// action_finalization_not_in_top10_consecutive_epochs is the consecutive epochs threshold
	// for EVIDENCE_TYPE_ACTION_FINALIZATION_NOT_IN_TOP_10.
	ActionFinalizationNotInTop10ConsecutiveEpochs uint32 `protobuf:"varint,16,opt,name=action_finalization_not_in_top10_consecutive_epochs,json=actionFinalizationNotInTop10ConsecutiveEpochs,proto3" json:"action_finalization_not_in_top10_consecutive_epochs,omitempty"`
	// action_finalization_recovery_epochs is the number of epochs to wait before considering recovery.
	ActionFinalizationRecoveryEpochs uint32 `protobuf:"varint,17,opt,name=action_finalization_recovery_epochs,json=actionFinalizationRecoveryEpochs,proto3" json:"action_finalization_recovery_epochs,omitempty"`
	// action_finalization_recovery_max_total_bad_evidences is the maximum allowed total count of bad
	// action-finalization evidences in the recovery epoch-span for auto-recovery to occur.
	// Recovery happens ONLY IF total_bad < this value.
	ActionFinalizationRecoveryMaxTotalBadEvidences uint32 `protobuf:"varint,18,opt,name=action_finalization_recovery_max_total_bad_evidences,json=actionFinalizationRecoveryMaxTotalBadEvidences,proto3" json:"action_finalization_recovery_max_total_bad_evidences,omitempty"`
	// Storage Challenge (SC) params.
	ScEnabled             bool   `protobuf:"varint,19,opt,name=sc_enabled,json=scEnabled,proto3" json:"sc_enabled,omitempty"`
	ScChallengersPerEpoch uint32 `protobuf:"varint,20,opt,name=sc_challengers_per_epoch,json=scChallengersPerEpoch,proto3" json:"sc_challengers_per_epoch,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_3788ca0fc7eb9d86, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetEpochLengthBlocks() uint64 {
	if m != nil {
		return m.EpochLengthBlocks
	}
	return 0
}

func (m *Params) GetEpochZeroHeight() uint64 {
	if m != nil {
		return m.EpochZeroHeight
	}
	return 0
}

func (m *Params) GetPeerQuorumReports() uint32 {
	if m != nil {
		return m.PeerQuorumReports
	}
	return 0
}

func (m *Params) GetMinProbeTargetsPerEpoch() uint32 {
	if m != nil {
		return m.MinProbeTargetsPerEpoch
	}
	return 0
}

func (m *Params) GetMaxProbeTargetsPerEpoch() uint32 {
	if m != nil {
		return m.MaxProbeTargetsPerEpoch
	}
	return 0
}

func (m *Params) GetRequiredOpenPorts() []uint32 {
	if m != nil {
		return m.RequiredOpenPorts
	}
	return nil
}

func (m *Params) GetMinCpuFreePercent() uint32 {
	if m != nil {
		return m.MinCpuFreePercent
	}
	return 0
}

func (m *Params) GetMinMemFreePercent() uint32 {
	if m != nil {
		return m.MinMemFreePercent
	}
	return 0
}

func (m *Params) GetMinDiskFreePercent() uint32 {
	if m != nil {
		return m.MinDiskFreePercent
	}
	return 0
}

func (m *Params) GetConsecutiveEpochsToPostpone() uint32 {
	if m != nil {
		return m.ConsecutiveEpochsToPostpone
	}
	return 0
}

func (m *Params) GetKeepLastEpochEntries() uint64 {
	if m != nil {
		return m.KeepLastEpochEntries
	}
	return 0
}

func (m *Params) GetPeerPortPostponeThresholdPercent() uint32 {
	if m != nil {
		return m.PeerPortPostponeThresholdPercent
	}
	return 0
}

func (m *Params) GetActionFinalizationSignatureFailureEvidencesPerEpoch() uint32 {
	if m != nil {
		return m.ActionFinalizationSignatureFailureEvidencesPerEpoch
	}
	return 0
}

func (m *Params) GetActionFinalizationSignatureFailureConsecutiveEpochs() uint32 {
	if m != nil {
		return m.ActionFinalizationSignatureFailureConsecutiveEpochs
	}
	return 0
}

func (m *Params) GetActionFinalizationNotInTop10EvidencesPerEpoch() uint32 {
	if m != nil {
		return m.ActionFinalizationNotInTop10EvidencesPerEpoch
	}
	return 0
}

func (m *Params) GetActionFinalizationNotInTop10ConsecutiveEpochs() uint32 {
	if m != nil {
		return m.ActionFinalizationNotInTop10ConsecutiveEpochs
	}
	return 0
}

func (m *Params) GetActionFinalizationRecoveryEpochs() uint32 {
	if m != nil {
		return m.ActionFinalizationRecoveryEpochs
	}
	return 0
}

func (m *Params) GetActionFinalizationRecoveryMaxTotalBadEvidences() uint32 {
	if m != nil {
		return m.ActionFinalizationRecoveryMaxTotalBadEvidences
	}
	return 0
}

func (m *Params) GetScEnabled() bool {
	if m != nil {
		return m.ScEnabled
	}
	return false
}

func (m *Params) GetScChallengersPerEpoch() uint32 {
	if m != nil {
		return m.ScChallengersPerEpoch
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "lumera.audit.v1.Params")
}

func init() { proto.RegisterFile("lumera/audit/v1/params.proto", fileDescriptor_3788ca0fc7eb9d86) }

var fileDescriptor_3788ca0fc7eb9d86 = []byte{
	// 715 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0x4f, 0x4f, 0x13, 0x41,
	0x18, 0xc6, 0x59, 0x41, 0x84, 0x41, 0x84, 0x2e, 0x25, 0x6c, 0x40, 0x6b, 0xa3, 0x1e, 0x08, 0x89,
	0xad, 0x0d, 0x1a, 0xff, 0xc4, 0x13, 0xb5, 0x44, 0x13, 0xc0, 0x5a, 0x7b, 0xe2, 0x32, 0x99, 0xee,
	0xbe, 0xb4, 0x63, 0x77, 0x67, 0x86, 0x99, 0xd9, 0xa6, 0x70, 0xf6, 0x03, 0xf8, 0x11, 0xfc, 0x38,
	0x1e, 0x39, 0x7a, 0x34, 0x70, 0xf1, 0x63, 0x98, 0x99, 0xe9, 0x96, 0x62, 0x4b, 0xe0, 0xd2, 0xee,
	0xce, 0xf3, 0xfe, 0x9e, 0x67, 0xde, 0x77, 0x36, 0x83, 0x1e, 0xc6, 0x69, 0x02, 0x92, 0x94, 0x49,
	0x1a, 0x51, 0x5d, 0xee, 0x55, 0xca, 0x82, 0x48, 0x92, 0xa8, 0x92, 0x90, 0x5c, 0x73, 0x7f, 0xc9,
	0xa9, 0x25, 0xab, 0x96, 0x7a, 0x95, 0xf5, 0x1c, 0x49, 0x28, 0xe3, 0x65, 0xfb, 0xeb, 0x6a, 0xd6,
	0xf3, 0x6d, 0xde, 0xe6, 0xf6, 0xb1, 0x6c, 0x9e, 0xdc, 0xea, 0x93, 0xef, 0x0b, 0x68, 0xb6, 0x6e,
	0xad, 0xfc, 0x12, 0x5a, 0x01, 0xc1, 0xc3, 0x0e, 0x8e, 0x81, 0xb5, 0x75, 0x07, 0xb7, 0x62, 0x1e,
	0x76, 0x55, 0xe0, 0x15, 0xbd, 0xcd, 0x99, 0x46, 0xce, 0x4a, 0x7b, 0x56, 0xd9, 0xb1, 0x82, 0xbf,
	0x85, 0xdc, 0x22, 0x3e, 0x05, 0xc9, 0x71, 0x07, 0x68, 0xbb, 0xa3, 0x83, 0x3b, 0xb6, 0x7a, 0xc9,
	0x0a, 0x87, 0x20, 0xf9, 0x47, 0xbb, 0x6c, 0xbc, 0x05, 0x80, 0xc4, 0xc7, 0x29, 0x97, 0x69, 0x82,
	0x25, 0x08, 0x2e, 0xb5, 0x0a, 0xa6, 0x8b, 0xde, 0xe6, 0x62, 0x23, 0x67, 0xa4, 0x2f, 0x56, 0x69,
	0x38, 0xc1, 0x7f, 0x8f, 0x36, 0x12, 0xca, 0xb0, 0x90, 0xbc, 0x05, 0x58, 0x13, 0xd9, 0x06, 0xad,
	0xb0, 0x00, 0x89, 0xad, 0x71, 0x30, 0x63, 0xb9, 0xb5, 0x84, 0xb2, 0xba, 0xa9, 0x68, 0xba, 0x82,
	0x3a, 0xc8, 0x9a, 0x91, 0x2d, 0x4d, 0xfa, 0xd7, 0xd2, 0x77, 0x07, 0x34, 0xe9, 0x4f, 0xa4, 0x4b,
	0x68, 0x45, 0xc2, 0x71, 0x4a, 0x25, 0x44, 0x98, 0x0b, 0x60, 0xd8, 0xed, 0x75, 0xb6, 0x38, 0x6d,
	0xf6, 0x9a, 0x49, 0x9f, 0x05, 0xb0, 0xba, 0xdd, 0x6b, 0x19, 0xe5, 0xcd, 0x5e, 0x43, 0x91, 0xe2,
	0x23, 0x09, 0x60, 0x82, 0x42, 0x60, 0x3a, 0xb8, 0xe7, 0x9a, 0x4b, 0x28, 0xab, 0x8a, 0x74, 0x57,
	0x02, 0xd4, 0x9d, 0x90, 0x01, 0x09, 0x24, 0x57, 0x81, 0xb9, 0x21, 0xb0, 0x0f, 0xc9, 0x28, 0x50,
	0x41, 0xab, 0x06, 0x88, 0xa8, 0xea, 0x5e, 0x25, 0xe6, 0x2d, 0xe1, 0x27, 0x94, 0x7d, 0xa0, 0xaa,
	0x3b, 0x8a, 0x54, 0x51, 0x21, 0xe4, 0x4c, 0x41, 0x98, 0x6a, 0xda, 0x03, 0xd7, 0xb8, 0xc2, 0x9a,
	0x63, 0xc1, 0x95, 0x16, 0x9c, 0x41, 0x80, 0x2c, 0xbb, 0x31, 0x52, 0x65, 0xdb, 0x57, 0x4d, 0x5e,
	0x1f, 0x94, 0xf8, 0xaf, 0xd0, 0x5a, 0x17, 0x40, 0xe0, 0x98, 0x28, 0xed, 0x2c, 0x30, 0x30, 0x2d,
	0x29, 0xa8, 0x60, 0xc1, 0x9e, 0x73, 0xde, 0xc8, 0x7b, 0x44, 0x69, 0x8b, 0xd6, 0x9c, 0xe6, 0x1f,
	0xa0, 0x67, 0xf6, 0xb0, 0xcd, 0xdc, 0x86, 0x79, 0x58, 0x77, 0x24, 0xa8, 0x0e, 0x8f, 0xa3, 0xe1,
	0xee, 0xef, 0xdb, 0x1d, 0x14, 0x4d, 0xad, 0x99, 0x64, 0x16, 0xdb, 0xcc, 0x0a, 0xb3, 0x5e, 0x7a,
	0xe8, 0x2d, 0x09, 0x35, 0xe5, 0x0c, 0x1f, 0x51, 0x46, 0x62, 0x7a, 0x4a, 0xec, 0x8b, 0xa2, 0x6d,
	0x46, 0x74, 0x2a, 0x01, 0x1f, 0x11, 0x1a, 0x9b, 0x7f, 0xe8, 0xd1, 0x08, 0x58, 0x08, 0xa3, 0x87,
	0xbd, 0x68, 0x43, 0xb6, 0x9d, 0xc1, 0xee, 0x08, 0xff, 0x35, 0xc3, 0x77, 0x1d, 0x5d, 0xcb, 0xe0,
	0xe1, 0x87, 0x90, 0xa2, 0x37, 0xb7, 0xcb, 0x1d, 0x9f, 0x74, 0xf0, 0xe0, 0xb6, 0xb1, 0xd5, 0xff,
	0xe7, 0xef, 0x77, 0xd1, 0xcb, 0x49, 0xb1, 0x8c, 0x6b, 0x4c, 0x19, 0xd6, 0x5c, 0x54, 0x5e, 0x4c,
	0xec, 0x74, 0xc9, 0x46, 0x3e, 0x1f, 0x8f, 0x3c, 0xe0, 0xfa, 0x13, 0x6b, 0x1a, 0x6e, 0xbc, 0xc7,
	0x6f, 0x68, 0xfb, 0xc6, 0xb0, 0x09, 0xed, 0x2d, 0xdf, 0x9c, 0x35, 0xde, 0xd8, 0x3e, 0x7a, 0x3a,
	0x29, 0x4b, 0x42, 0xc8, 0x7b, 0x20, 0x4f, 0x32, 0xef, 0x9c, 0xfb, 0x2c, 0xc6, 0xbd, 0x1b, 0x83,
	0xc2, 0x81, 0x5d, 0x3c, 0x79, 0x4e, 0x43, 0x3b, 0x73, 0x05, 0x68, 0xae, 0x49, 0x8c, 0x5b, 0x24,
	0xba, 0x9c, 0x58, 0xe0, 0x5b, 0xff, 0xd2, 0xf5, 0xfe, 0xfb, 0xa4, 0xdf, 0x34, 0xdc, 0x0e, 0x89,
	0x86, 0x03, 0xf3, 0x1f, 0x21, 0xa4, 0x42, 0x0c, 0x8c, 0xb4, 0x62, 0x88, 0x82, 0x95, 0xa2, 0xb7,
	0x39, 0xd7, 0x98, 0x57, 0x61, 0xcd, 0x2d, 0xf8, 0xaf, 0x51, 0xa0, 0x42, 0x1c, 0x76, 0x48, 0x6c,
	0x6e, 0x4f, 0x90, 0xa3, 0x07, 0x93, 0xb7, 0x81, 0xab, 0x2a, 0xac, 0x5e, 0xca, 0xd9, 0x01, 0xbc,
	0x9b, 0xf9, 0xfb, 0xf3, 0xb1, 0xb7, 0xb3, 0xf5, 0xeb, 0xbc, 0xe0, 0x9d, 0x9d, 0x17, 0xbc, 0x3f,
	0xe7, 0x05, 0xef, 0xc7, 0x45, 0x61, 0xea, 0xec, 0xa2, 0x30, 0xf5, 0xfb, 0xa2, 0x30, 0x75, 0xb8,
	0xdc, 0xbf, 0xbc, 0xf3, 0xf5, 0x89, 0x00, 0xd5, 0x9a, 0xb5, 0x37, 0xf7, 0xf6, 0xbf, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xf4, 0x64, 0xdc, 0x58, 0x13, 0x06, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.EpochLengthBlocks != that1.EpochLengthBlocks {
		return false
	}
	if this.EpochZeroHeight != that1.EpochZeroHeight {
		return false
	}
	if this.PeerQuorumReports != that1.PeerQuorumReports {
		return false
	}
	if this.MinProbeTargetsPerEpoch != that1.MinProbeTargetsPerEpoch {
		return false
	}
	if this.MaxProbeTargetsPerEpoch != that1.MaxProbeTargetsPerEpoch {
		return false
	}
	if len(this.RequiredOpenPorts) != len(that1.RequiredOpenPorts) {
		return false
	}
	for i := range this.RequiredOpenPorts {
		if this.RequiredOpenPorts[i] != that1.RequiredOpenPorts[i] {
			return false
		}
	}
	if this.MinCpuFreePercent != that1.MinCpuFreePercent {
		return false
	}
	if this.MinMemFreePercent != that1.MinMemFreePercent {
		return false
	}
	if this.MinDiskFreePercent != that1.MinDiskFreePercent {
		return false
	}
	if this.ConsecutiveEpochsToPostpone != that1.ConsecutiveEpochsToPostpone {
		return false
	}
	if this.KeepLastEpochEntries != that1.KeepLastEpochEntries {
		return false
	}
	if this.PeerPortPostponeThresholdPercent != that1.PeerPortPostponeThresholdPercent {
		return false
	}
	if this.ActionFinalizationSignatureFailureEvidencesPerEpoch != that1.ActionFinalizationSignatureFailureEvidencesPerEpoch {
		return false
	}
	if this.ActionFinalizationSignatureFailureConsecutiveEpochs != that1.ActionFinalizationSignatureFailureConsecutiveEpochs {
		return false
	}
	if this.ActionFinalizationNotInTop10EvidencesPerEpoch != that1.ActionFinalizationNotInTop10EvidencesPerEpoch {
		return false
	}
	if this.ActionFinalizationNotInTop10ConsecutiveEpochs != that1.ActionFinalizationNotInTop10ConsecutiveEpochs {
		return false
	}
	if this.ActionFinalizationRecoveryEpochs != that1.ActionFinalizationRecoveryEpochs {
		return false
	}
	if this.ActionFinalizationRecoveryMaxTotalBadEvidences != that1.ActionFinalizationRecoveryMaxTotalBadEvidences {
		return false
	}
	if this.ScEnabled != that1.ScEnabled {
		return false
	}
	if this.ScChallengersPerEpoch != that1.ScChallengersPerEpoch {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ScChallengersPerEpoch != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.ScChallengersPerEpoch))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xa0
	}
	if m.ScEnabled {
		i--
		if m.ScEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x98
	}
	if m.ActionFinalizationRecoveryMaxTotalBadEvidences != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.ActionFinalizationRecoveryMaxTotalBadEvidences))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x90
	}
	if m.ActionFinalizationRecoveryEpochs != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.ActionFinalizationRecoveryEpochs))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x88
	}
	if m.ActionFinalizationNotInTop10ConsecutiveEpochs != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.ActionFinalizationNotInTop10ConsecutiveEpochs))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x80
	}
	if m.ActionFinalizationNotInTop10EvidencesPerEpoch != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.ActionFinalizationNotInTop10EvidencesPerEpoch))
		i--
		dAtA[i] = 0x78
	}
	if m.ActionFinalizationSignatureFailureConsecutiveEpochs != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.ActionFinalizationSignatureFailureConsecutiveEpochs))
		i--
		dAtA[i] = 0x70
	}
	if m.ActionFinalizationSignatureFailureEvidencesPerEpoch != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.ActionFinalizationSignatureFailureEvidencesPerEpoch))
		i--
		dAtA[i] = 0x68
	}
	if m.PeerPortPostponeThresholdPercent != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.PeerPortPostponeThresholdPercent))
		i--
		dAtA[i] = 0x60
	}
	if m.KeepLastEpochEntries != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.KeepLastEpochEntries))
		i--
		dAtA[i] = 0x58
	}
	if m.ConsecutiveEpochsToPostpone != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.ConsecutiveEpochsToPostpone))
		i--
		dAtA[i] = 0x50
	}
	if m.MinDiskFreePercent != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MinDiskFreePercent))
		i--
		dAtA[i] = 0x48
	}
	if m.MinMemFreePercent != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MinMemFreePercent))
		i--
		dAtA[i] = 0x40
	}
	if m.MinCpuFreePercent != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MinCpuFreePercent))
		i--
		dAtA[i] = 0x38
	}
	if len(m.RequiredOpenPorts) > 0 {
		dAtA2 := make([]byte, len(m.RequiredOpenPorts)*10)
		var j1 int
		for _, num := range m.RequiredOpenPorts {
			for num >= 1<<7 {
				dAtA2[j1] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j1++
			}
			dAtA2[j1] = uint8(num)
			j1++
		}
		i -= j1
		copy(dAtA[i:], dAtA2[:j1])
		i = encodeVarintParams(dAtA, i, uint64(j1))
		i--
		dAtA[i] = 0x32
	}
	if m.MaxProbeTargetsPerEpoch != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxProbeTargetsPerEpoch))
		i--
		dAtA[i] = 0x28
	}
	if m.MinProbeTargetsPerEpoch != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MinProbeTargetsPerEpoch))
		i--
		dAtA[i] = 0x20
	}
	if m.PeerQuorumReports != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.PeerQuorumReports))
		i--
		dAtA[i] = 0x18
	}
	if m.EpochZeroHeight != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.EpochZeroHeight))
		i--
		dAtA[i] = 0x10
	}
	if m.EpochLengthBlocks != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.EpochLengthBlocks))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.EpochLengthBlocks != 0 {
		n += 1 + sovParams(uint64(m.EpochLengthBlocks))
	}
	if m.EpochZeroHeight != 0 {
		n += 1 + sovParams(uint64(m.EpochZeroHeight))
	}
	if m.PeerQuorumReports != 0 {
		n += 1 + sovParams(uint64(m.PeerQuorumReports))
	}
	if m.MinProbeTargetsPerEpoch != 0 {
		n += 1 + sovParams(uint64(m.MinProbeTargetsPerEpoch))
	}
	if m.MaxProbeTargetsPerEpoch != 0 {
		n += 1 + sovParams(uint64(m.MaxProbeTargetsPerEpoch))
	}
	if len(m.RequiredOpenPorts) > 0 {
		l = 0
		for _, e := range m.RequiredOpenPorts {
			l += sovParams(uint64(e))
		}
		n += 1 + sovParams(uint64(l)) + l
	}
	if m.MinCpuFreePercent != 0 {
		n += 1 + sovParams(uint64(m.MinCpuFreePercent))
	}
	if m.MinMemFreePercent != 0 {
		n += 1 + sovParams(uint64(m.MinMemFreePercent))
	}
	if m.MinDiskFreePercent != 0 {
		n += 1 + sovParams(uint64(m.MinDiskFreePercent))
	}
	if m.ConsecutiveEpochsToPostpone != 0 {
		n += 1 + sovParams(uint64(m.ConsecutiveEpochsToPostpone))
	}
	if m.KeepLastEpochEntries != 0 {
		n += 1 + sovParams(uint64(m.KeepLastEpochEntries))
	}
	if m.PeerPortPostponeThresholdPercent != 0 {
		n += 1 + sovParams(uint64(m.PeerPortPostponeThresholdPercent))
	}
	if m.ActionFinalizationSignatureFailureEvidencesPerEpoch != 0 {
		n += 1 + sovParams(uint64(m.ActionFinalizationSignatureFailureEvidencesPerEpoch))
	}
	if m.ActionFinalizationSignatureFailureConsecutiveEpochs != 0 {
		n += 1 + sovParams(uint64(m.ActionFinalizationSignatureFailureConsecutiveEpochs))
	}
	if m.ActionFinalizationNotInTop10EvidencesPerEpoch != 0 {
		n += 1 + sovParams(uint64(m.ActionFinalizationNotInTop10EvidencesPerEpoch))
	}
	if m.ActionFinalizationNotInTop10ConsecutiveEpochs != 0 {
		n += 2 + sovParams(uint64(m.ActionFinalizationNotInTop10ConsecutiveEpochs))
	}
	if m.ActionFinalizationRecoveryEpochs != 0 {
		n += 2 + sovParams(uint64(m.ActionFinalizationRecoveryEpochs))
	}
	if m.ActionFinalizationRecoveryMaxTotalBadEvidences != 0 {
		n += 2 + sovParams(uint64(m.ActionFinalizationRecoveryMaxTotalBadEvidences))
	}
	if m.ScEnabled {
		n += 3
	}
	if m.ScChallengersPerEpoch != 0 {
		n += 2 + sovParams(uint64(m.ScChallengersPerEpoch))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochLengthBlocks", wireType)
			}
			m.EpochLengthBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EpochLengthBlocks |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochZeroHeight", wireType)
			}
			m.EpochZeroHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EpochZeroHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PeerQuorumReports", wireType)
			}
			m.PeerQuorumReports = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PeerQuorumReports |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinProbeTargetsPerEpoch", wireType)
			}
			m.MinProbeTargetsPerEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinProbeTargetsPerEpoch |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxProbeTargetsPerEpoch", wireType)
			}
			m.MaxProbeTargetsPerEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxProbeTargetsPerEpoch |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType == 0 {
				var v uint32
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowParams
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint32(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.RequiredOpenPorts = append(m.RequiredOpenPorts, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowParams
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthParams
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthParams
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.RequiredOpenPorts) == 0 {
					m.RequiredOpenPorts = make([]uint32, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint32
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowParams
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint32(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.RequiredOpenPorts = append(m.RequiredOpenPorts, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field RequiredOpenPorts", wireType)
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinCpuFreePercent", wireType)
			}
			m.MinCpuFreePercent = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinCpuFreePercent |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinMemFreePercent", wireType)
			}
			m.MinMemFreePercent = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinMemFreePercent |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinDiskFreePercent", wireType)
			}
			m.MinDiskFreePercent = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinDiskFreePercent |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsecutiveEpochsToPostpone", wireType)
			}
			m.ConsecutiveEpochsToPostpone = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ConsecutiveEpochsToPostpone |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field KeepLastEpochEntries", wireType)
			}
			m.KeepLastEpochEntries = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.KeepLastEpochEntries |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PeerPortPostponeThresholdPercent", wireType)
			}
			m.PeerPortPostponeThresholdPercent = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PeerPortPostponeThresholdPercent |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActionFinalizationSignatureFailureEvidencesPerEpoch", wireType)
			}
			m.ActionFinalizationSignatureFailureEvidencesPerEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ActionFinalizationSignatureFailureEvidencesPerEpoch |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActionFinalizationSignatureFailureConsecutiveEpochs", wireType)
			}
			m.ActionFinalizationSignatureFailureConsecutiveEpochs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ActionFinalizationSignatureFailureConsecutiveEpochs |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 15:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActionFinalizationNotInTop10EvidencesPerEpoch", wireType)
			}
			m.ActionFinalizationNotInTop10EvidencesPerEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ActionFinalizationNotInTop10EvidencesPerEpoch |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 16:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActionFinalizationNotInTop10ConsecutiveEpochs", wireType)
			}
			m.ActionFinalizationNotInTop10ConsecutiveEpochs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ActionFinalizationNotInTop10ConsecutiveEpochs |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 17:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActionFinalizationRecoveryEpochs", wireType)
			}
			m.ActionFinalizationRecoveryEpochs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ActionFinalizationRecoveryEpochs |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 18:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActionFinalizationRecoveryMaxTotalBadEvidences", wireType)
			}
			m.ActionFinalizationRecoveryMaxTotalBadEvidences = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ActionFinalizationRecoveryMaxTotalBadEvidences |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 19:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ScEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.ScEnabled = bool(v != 0)
		case 20:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ScChallengersPerEpoch", wireType)
			}
			m.ScChallengersPerEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ScChallengersPerEpoch |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
