// Copyright (c) 2024-2025 The Lumera developers
//

// Code generated by MockGen. DO NOT EDIT.
// Source: expected_keepers.go
//
// Generated by this command:
//
//	mockgen -copyright_file=../../../../testutil/mock_header.txt -destination=../mocks/expected_keepers_mock.go -package=supernodemocks -source=expected_keepers.go
//

// Package supernodemocks is a generated GoMock package.
package supernodemocks

import (
	context "context"
	reflect "reflect"
	time "time"

	address "cosmossdk.io/core/address"
	log "cosmossdk.io/log"
	math "cosmossdk.io/math"
	types "github.com/LumeraProtocol/lumera/x/audit/v1/types"
	types0 "github.com/LumeraProtocol/lumera/x/supernode/v1/types"
	types1 "github.com/cosmos/cosmos-sdk/types"
	query "github.com/cosmos/cosmos-sdk/types/query"
	types2 "github.com/cosmos/cosmos-sdk/x/staking/types"
	gomock "go.uber.org/mock/gomock"
)

// MockSupernodeKeeper is a mock of SupernodeKeeper interface.
type MockSupernodeKeeper struct {
	ctrl     *gomock.Controller
	recorder *MockSupernodeKeeperMockRecorder
	isgomock struct{}
}

// MockSupernodeKeeperMockRecorder is the mock recorder for MockSupernodeKeeper.
type MockSupernodeKeeperMockRecorder struct {
	mock *MockSupernodeKeeper
}

// NewMockSupernodeKeeper creates a new mock instance.
func NewMockSupernodeKeeper(ctrl *gomock.Controller) *MockSupernodeKeeper {
	mock := &MockSupernodeKeeper{ctrl: ctrl}
	mock.recorder = &MockSupernodeKeeperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSupernodeKeeper) EXPECT() *MockSupernodeKeeperMockRecorder {
	return m.recorder
}

// CheckValidatorSupernodeEligibility mocks base method.
func (m *MockSupernodeKeeper) CheckValidatorSupernodeEligibility(ctx types1.Context, validator types2.ValidatorI, valAddr, supernodeAccount string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckValidatorSupernodeEligibility", ctx, validator, valAddr, supernodeAccount)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckValidatorSupernodeEligibility indicates an expected call of CheckValidatorSupernodeEligibility.
func (mr *MockSupernodeKeeperMockRecorder) CheckValidatorSupernodeEligibility(ctx, validator, valAddr, supernodeAccount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckValidatorSupernodeEligibility", reflect.TypeOf((*MockSupernodeKeeper)(nil).CheckValidatorSupernodeEligibility), ctx, validator, valAddr, supernodeAccount)
}

// CountEligibleSNs mocks base method.
func (m *MockSupernodeKeeper) CountEligibleSNs(ctx types1.Context) uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountEligibleSNs", ctx)
	ret0, _ := ret[0].(uint64)
	return ret0
}

// CountEligibleSNs indicates an expected call of CountEligibleSNs.
func (mr *MockSupernodeKeeperMockRecorder) CountEligibleSNs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountEligibleSNs", reflect.TypeOf((*MockSupernodeKeeper)(nil).CountEligibleSNs), ctx)
}

// DeleteMetricsState mocks base method.
func (m *MockSupernodeKeeper) DeleteMetricsState(ctx types1.Context, valAddr types1.ValAddress) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeleteMetricsState", ctx, valAddr)
}

// DeleteMetricsState indicates an expected call of DeleteMetricsState.
func (mr *MockSupernodeKeeperMockRecorder) DeleteMetricsState(ctx, valAddr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMetricsState", reflect.TypeOf((*MockSupernodeKeeper)(nil).DeleteMetricsState), ctx, valAddr)
}

// DeleteSuperNode mocks base method.
func (m *MockSupernodeKeeper) DeleteSuperNode(ctx types1.Context, valAddr types1.ValAddress) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeleteSuperNode", ctx, valAddr)
}

// DeleteSuperNode indicates an expected call of DeleteSuperNode.
func (mr *MockSupernodeKeeperMockRecorder) DeleteSuperNode(ctx, valAddr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSuperNode", reflect.TypeOf((*MockSupernodeKeeper)(nil).DeleteSuperNode), ctx, valAddr)
}

// EnsureModuleAccount mocks base method.
func (m *MockSupernodeKeeper) EnsureModuleAccount(ctx types1.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "EnsureModuleAccount", ctx)
}

// EnsureModuleAccount indicates an expected call of EnsureModuleAccount.
func (mr *MockSupernodeKeeperMockRecorder) EnsureModuleAccount(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureModuleAccount", reflect.TypeOf((*MockSupernodeKeeper)(nil).EnsureModuleAccount), ctx)
}

// GetAllSuperNodes mocks base method.
func (m *MockSupernodeKeeper) GetAllSuperNodes(ctx types1.Context, stateFilters ...types0.SuperNodeState) ([]types0.SuperNode, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range stateFilters {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAllSuperNodes", varargs...)
	ret0, _ := ret[0].([]types0.SuperNode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllSuperNodes indicates an expected call of GetAllSuperNodes.
func (mr *MockSupernodeKeeperMockRecorder) GetAllSuperNodes(ctx any, stateFilters ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, stateFilters...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllSuperNodes", reflect.TypeOf((*MockSupernodeKeeper)(nil).GetAllSuperNodes), varargs...)
}

// GetAuthority mocks base method.
func (m *MockSupernodeKeeper) GetAuthority() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuthority")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetAuthority indicates an expected call of GetAuthority.
func (mr *MockSupernodeKeeperMockRecorder) GetAuthority() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuthority", reflect.TypeOf((*MockSupernodeKeeper)(nil).GetAuthority))
}

// GetBlockHashForHeight mocks base method.
func (m *MockSupernodeKeeper) GetBlockHashForHeight(ctx types1.Context, height int64) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlockHashForHeight", ctx, height)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlockHashForHeight indicates an expected call of GetBlockHashForHeight.
func (mr *MockSupernodeKeeperMockRecorder) GetBlockHashForHeight(ctx, height any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlockHashForHeight", reflect.TypeOf((*MockSupernodeKeeper)(nil).GetBlockHashForHeight), ctx, height)
}

// GetLastDistributionHeight mocks base method.
func (m *MockSupernodeKeeper) GetLastDistributionHeight(ctx types1.Context) int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastDistributionHeight", ctx)
	ret0, _ := ret[0].(int64)
	return ret0
}

// GetLastDistributionHeight indicates an expected call of GetLastDistributionHeight.
func (mr *MockSupernodeKeeperMockRecorder) GetLastDistributionHeight(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastDistributionHeight", reflect.TypeOf((*MockSupernodeKeeper)(nil).GetLastDistributionHeight), ctx)
}

// GetLatestCascadeBytesForPayout mocks base method.
func (m *MockSupernodeKeeper) GetLatestCascadeBytesForPayout(ctx types1.Context, supernodeAccount string) (float64, int64, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestCascadeBytesForPayout", ctx, supernodeAccount)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(bool)
	return ret0, ret1, ret2
}

// GetLatestCascadeBytesForPayout indicates an expected call of GetLatestCascadeBytesForPayout.
func (mr *MockSupernodeKeeperMockRecorder) GetLatestCascadeBytesForPayout(ctx, supernodeAccount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestCascadeBytesForPayout", reflect.TypeOf((*MockSupernodeKeeper)(nil).GetLatestCascadeBytesForPayout), ctx, supernodeAccount)
}

// GetMetricsState mocks base method.
func (m *MockSupernodeKeeper) GetMetricsState(ctx types1.Context, valAddr types1.ValAddress) (types0.SupernodeMetricsState, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetricsState", ctx, valAddr)
	ret0, _ := ret[0].(types0.SupernodeMetricsState)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetMetricsState indicates an expected call of GetMetricsState.
func (mr *MockSupernodeKeeperMockRecorder) GetMetricsState(ctx, valAddr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetricsState", reflect.TypeOf((*MockSupernodeKeeper)(nil).GetMetricsState), ctx, valAddr)
}

// GetParams mocks base method.
func (m *MockSupernodeKeeper) GetParams(ctx types1.Context) types0.Params {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetParams", ctx)
	ret0, _ := ret[0].(types0.Params)
	return ret0
}

// GetParams indicates an expected call of GetParams.
func (mr *MockSupernodeKeeperMockRecorder) GetParams(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetParams", reflect.TypeOf((*MockSupernodeKeeper)(nil).GetParams), ctx)
}

// GetPoolBalance mocks base method.
func (m *MockSupernodeKeeper) GetPoolBalance(ctx types1.Context) types1.Coins {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPoolBalance", ctx)
	ret0, _ := ret[0].(types1.Coins)
	return ret0
}

// GetPoolBalance indicates an expected call of GetPoolBalance.
func (mr *MockSupernodeKeeperMockRecorder) GetPoolBalance(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPoolBalance", reflect.TypeOf((*MockSupernodeKeeper)(nil).GetPoolBalance), ctx)
}

// GetRegistrationFeeShareBps mocks base method.
func (m *MockSupernodeKeeper) GetRegistrationFeeShareBps(ctx types1.Context) uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRegistrationFeeShareBps", ctx)
	ret0, _ := ret[0].(uint64)
	return ret0
}

// GetRegistrationFeeShareBps indicates an expected call of GetRegistrationFeeShareBps.
func (mr *MockSupernodeKeeperMockRecorder) GetRegistrationFeeShareBps(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRegistrationFeeShareBps", reflect.TypeOf((*MockSupernodeKeeper)(nil).GetRegistrationFeeShareBps), ctx)
}

// GetSNDistState mocks base method.
func (m *MockSupernodeKeeper) GetSNDistState(ctx types1.Context, valAddr string) (types0.SNDistState, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSNDistState", ctx, valAddr)
	ret0, _ := ret[0].(types0.SNDistState)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetSNDistState indicates an expected call of GetSNDistState.
func (mr *MockSupernodeKeeperMockRecorder) GetSNDistState(ctx, valAddr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSNDistState", reflect.TypeOf((*MockSupernodeKeeper)(nil).GetSNDistState), ctx, valAddr)
}

// GetStakingKeeper mocks base method.
func (m *MockSupernodeKeeper) GetStakingKeeper() types0.StakingKeeper {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStakingKeeper")
	ret0, _ := ret[0].(types0.StakingKeeper)
	return ret0
}

// GetStakingKeeper indicates an expected call of GetStakingKeeper.
func (mr *MockSupernodeKeeperMockRecorder) GetStakingKeeper() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStakingKeeper", reflect.TypeOf((*MockSupernodeKeeper)(nil).GetStakingKeeper))
}

// GetSuperNodeByAccount mocks base method.
func (m *MockSupernodeKeeper) GetSuperNodeByAccount(ctx types1.Context, supernodeAccount string) (types0.SuperNode, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSuperNodeByAccount", ctx, supernodeAccount)
	ret0, _ := ret[0].(types0.SuperNode)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetSuperNodeByAccount indicates an expected call of GetSuperNodeByAccount.
func (mr *MockSupernodeKeeperMockRecorder) GetSuperNodeByAccount(ctx, supernodeAccount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSuperNodeByAccount", reflect.TypeOf((*MockSupernodeKeeper)(nil).GetSuperNodeByAccount), ctx, supernodeAccount)
}

// GetSuperNodesPaginated mocks base method.
func (m *MockSupernodeKeeper) GetSuperNodesPaginated(ctx types1.Context, pagination *query.PageRequest, stateFilters ...types0.SuperNodeState) ([]*types0.SuperNode, *query.PageResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, pagination}
	for _, a := range stateFilters {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetSuperNodesPaginated", varargs...)
	ret0, _ := ret[0].([]*types0.SuperNode)
	ret1, _ := ret[1].(*query.PageResponse)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetSuperNodesPaginated indicates an expected call of GetSuperNodesPaginated.
func (mr *MockSupernodeKeeperMockRecorder) GetSuperNodesPaginated(ctx, pagination any, stateFilters ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, pagination}, stateFilters...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSuperNodesPaginated", reflect.TypeOf((*MockSupernodeKeeper)(nil).GetSuperNodesPaginated), varargs...)
}

// GetTotalDistributed mocks base method.
func (m *MockSupernodeKeeper) GetTotalDistributed(ctx types1.Context) types1.Coins {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalDistributed", ctx)
	ret0, _ := ret[0].(types1.Coins)
	return ret0
}

// GetTotalDistributed indicates an expected call of GetTotalDistributed.
func (mr *MockSupernodeKeeperMockRecorder) GetTotalDistributed(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalDistributed", reflect.TypeOf((*MockSupernodeKeeper)(nil).GetTotalDistributed), ctx)
}

// IsEligibleAndNotJailedValidator mocks base method.
func (m *MockSupernodeKeeper) IsEligibleAndNotJailedValidator(ctx types1.Context, valAddr types1.ValAddress) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsEligibleAndNotJailedValidator", ctx, valAddr)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsEligibleAndNotJailedValidator indicates an expected call of IsEligibleAndNotJailedValidator.
func (mr *MockSupernodeKeeperMockRecorder) IsEligibleAndNotJailedValidator(ctx, valAddr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsEligibleAndNotJailedValidator", reflect.TypeOf((*MockSupernodeKeeper)(nil).IsEligibleAndNotJailedValidator), ctx, valAddr)
}

// IsSuperNodeActive mocks base method.
func (m *MockSupernodeKeeper) IsSuperNodeActive(ctx types1.Context, valAddr types1.ValAddress) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSuperNodeActive", ctx, valAddr)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsSuperNodeActive indicates an expected call of IsSuperNodeActive.
func (mr *MockSupernodeKeeperMockRecorder) IsSuperNodeActive(ctx, valAddr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSuperNodeActive", reflect.TypeOf((*MockSupernodeKeeper)(nil).IsSuperNodeActive), ctx, valAddr)
}

// Logger mocks base method.
func (m *MockSupernodeKeeper) Logger() log.Logger {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logger")
	ret0, _ := ret[0].(log.Logger)
	return ret0
}

// Logger indicates an expected call of Logger.
func (mr *MockSupernodeKeeperMockRecorder) Logger() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logger", reflect.TypeOf((*MockSupernodeKeeper)(nil).Logger))
}

// QuerySuperNode mocks base method.
func (m *MockSupernodeKeeper) QuerySuperNode(ctx types1.Context, valOperAddr types1.ValAddress) (types0.SuperNode, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QuerySuperNode", ctx, valOperAddr)
	ret0, _ := ret[0].(types0.SuperNode)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// QuerySuperNode indicates an expected call of QuerySuperNode.
func (mr *MockSupernodeKeeperMockRecorder) QuerySuperNode(ctx, valOperAddr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QuerySuperNode", reflect.TypeOf((*MockSupernodeKeeper)(nil).QuerySuperNode), ctx, valOperAddr)
}

// RankSuperNodesByDistance mocks base method.
func (m *MockSupernodeKeeper) RankSuperNodesByDistance(blockHash []byte, supernodes []types0.SuperNode, topN int) []types0.SuperNode {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RankSuperNodesByDistance", blockHash, supernodes, topN)
	ret0, _ := ret[0].([]types0.SuperNode)
	return ret0
}

// RankSuperNodesByDistance indicates an expected call of RankSuperNodesByDistance.
func (mr *MockSupernodeKeeperMockRecorder) RankSuperNodesByDistance(blockHash, supernodes, topN any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RankSuperNodesByDistance", reflect.TypeOf((*MockSupernodeKeeper)(nil).RankSuperNodesByDistance), blockHash, supernodes, topN)
}

// RecoverSuperNodeFromPostponed mocks base method.
func (m *MockSupernodeKeeper) RecoverSuperNodeFromPostponed(ctx types1.Context, valAddr types1.ValAddress) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecoverSuperNodeFromPostponed", ctx, valAddr)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecoverSuperNodeFromPostponed indicates an expected call of RecoverSuperNodeFromPostponed.
func (mr *MockSupernodeKeeperMockRecorder) RecoverSuperNodeFromPostponed(ctx, valAddr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecoverSuperNodeFromPostponed", reflect.TypeOf((*MockSupernodeKeeper)(nil).RecoverSuperNodeFromPostponed), ctx, valAddr)
}

// SetLastDistributionHeight mocks base method.
func (m *MockSupernodeKeeper) SetLastDistributionHeight(ctx types1.Context, height int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetLastDistributionHeight", ctx, height)
}

// SetLastDistributionHeight indicates an expected call of SetLastDistributionHeight.
func (mr *MockSupernodeKeeperMockRecorder) SetLastDistributionHeight(ctx, height any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLastDistributionHeight", reflect.TypeOf((*MockSupernodeKeeper)(nil).SetLastDistributionHeight), ctx, height)
}

// SetMetricsState mocks base method.
func (m *MockSupernodeKeeper) SetMetricsState(ctx types1.Context, state types0.SupernodeMetricsState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMetricsState", ctx, state)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetMetricsState indicates an expected call of SetMetricsState.
func (mr *MockSupernodeKeeperMockRecorder) SetMetricsState(ctx, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMetricsState", reflect.TypeOf((*MockSupernodeKeeper)(nil).SetMetricsState), ctx, state)
}

// SetParams mocks base method.
func (m *MockSupernodeKeeper) SetParams(ctx types1.Context, params types0.Params) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetParams", ctx, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetParams indicates an expected call of SetParams.
func (mr *MockSupernodeKeeperMockRecorder) SetParams(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetParams", reflect.TypeOf((*MockSupernodeKeeper)(nil).SetParams), ctx, params)
}

// SetSuperNode mocks base method.
func (m *MockSupernodeKeeper) SetSuperNode(ctx types1.Context, supernode types0.SuperNode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSuperNode", ctx, supernode)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetSuperNode indicates an expected call of SetSuperNode.
func (mr *MockSupernodeKeeperMockRecorder) SetSuperNode(ctx, supernode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSuperNode", reflect.TypeOf((*MockSupernodeKeeper)(nil).SetSuperNode), ctx, supernode)
}

// SetSuperNodeActive mocks base method.
func (m *MockSupernodeKeeper) SetSuperNodeActive(ctx types1.Context, valAddr types1.ValAddress, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSuperNodeActive", ctx, valAddr, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetSuperNodeActive indicates an expected call of SetSuperNodeActive.
func (mr *MockSupernodeKeeperMockRecorder) SetSuperNodeActive(ctx, valAddr, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSuperNodeActive", reflect.TypeOf((*MockSupernodeKeeper)(nil).SetSuperNodeActive), ctx, valAddr, reason)
}

// SetSuperNodePostponed mocks base method.
func (m *MockSupernodeKeeper) SetSuperNodePostponed(ctx types1.Context, valAddr types1.ValAddress, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSuperNodePostponed", ctx, valAddr, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetSuperNodePostponed indicates an expected call of SetSuperNodePostponed.
func (mr *MockSupernodeKeeperMockRecorder) SetSuperNodePostponed(ctx, valAddr, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSuperNodePostponed", reflect.TypeOf((*MockSupernodeKeeper)(nil).SetSuperNodePostponed), ctx, valAddr, reason)
}

// SetSuperNodeStopped mocks base method.
func (m *MockSupernodeKeeper) SetSuperNodeStopped(ctx types1.Context, valAddr types1.ValAddress, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSuperNodeStopped", ctx, valAddr, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetSuperNodeStopped indicates an expected call of SetSuperNodeStopped.
func (mr *MockSupernodeKeeperMockRecorder) SetSuperNodeStopped(ctx, valAddr, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSuperNodeStopped", reflect.TypeOf((*MockSupernodeKeeper)(nil).SetSuperNodeStopped), ctx, valAddr, reason)
}

// MockStakingKeeper is a mock of StakingKeeper interface.
type MockStakingKeeper struct {
	ctrl     *gomock.Controller
	recorder *MockStakingKeeperMockRecorder
	isgomock struct{}
}

// MockStakingKeeperMockRecorder is the mock recorder for MockStakingKeeper.
type MockStakingKeeperMockRecorder struct {
	mock *MockStakingKeeper
}

// NewMockStakingKeeper creates a new mock instance.
func NewMockStakingKeeper(ctrl *gomock.Controller) *MockStakingKeeper {
	mock := &MockStakingKeeper{ctrl: ctrl}
	mock.recorder = &MockStakingKeeperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStakingKeeper) EXPECT() *MockStakingKeeperMockRecorder {
	return m.recorder
}

// ConsensusAddressCodec mocks base method.
func (m *MockStakingKeeper) ConsensusAddressCodec() address.Codec {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConsensusAddressCodec")
	ret0, _ := ret[0].(address.Codec)
	return ret0
}

// ConsensusAddressCodec indicates an expected call of ConsensusAddressCodec.
func (mr *MockStakingKeeperMockRecorder) ConsensusAddressCodec() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConsensusAddressCodec", reflect.TypeOf((*MockStakingKeeper)(nil).ConsensusAddressCodec))
}

// Delegation mocks base method.
func (m *MockStakingKeeper) Delegation(ctx context.Context, delAddr types1.AccAddress, valAddr types1.ValAddress) (types2.DelegationI, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delegation", ctx, delAddr, valAddr)
	ret0, _ := ret[0].(types2.DelegationI)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delegation indicates an expected call of Delegation.
func (mr *MockStakingKeeperMockRecorder) Delegation(ctx, delAddr, valAddr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delegation", reflect.TypeOf((*MockStakingKeeper)(nil).Delegation), ctx, delAddr, valAddr)
}

// Validator mocks base method.
func (m *MockStakingKeeper) Validator(arg0 context.Context, arg1 types1.ValAddress) (types2.ValidatorI, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validator", arg0, arg1)
	ret0, _ := ret[0].(types2.ValidatorI)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Validator indicates an expected call of Validator.
func (mr *MockStakingKeeperMockRecorder) Validator(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validator", reflect.TypeOf((*MockStakingKeeper)(nil).Validator), arg0, arg1)
}

// ValidatorByConsAddr mocks base method.
func (m *MockStakingKeeper) ValidatorByConsAddr(arg0 context.Context, arg1 types1.ConsAddress) (types2.ValidatorI, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidatorByConsAddr", arg0, arg1)
	ret0, _ := ret[0].(types2.ValidatorI)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidatorByConsAddr indicates an expected call of ValidatorByConsAddr.
func (mr *MockStakingKeeperMockRecorder) ValidatorByConsAddr(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidatorByConsAddr", reflect.TypeOf((*MockStakingKeeper)(nil).ValidatorByConsAddr), arg0, arg1)
}

// MockAuditKeeper is a mock of AuditKeeper interface.
type MockAuditKeeper struct {
	ctrl     *gomock.Controller
	recorder *MockAuditKeeperMockRecorder
	isgomock struct{}
}

// MockAuditKeeperMockRecorder is the mock recorder for MockAuditKeeper.
type MockAuditKeeperMockRecorder struct {
	mock *MockAuditKeeper
}

// NewMockAuditKeeper creates a new mock instance.
func NewMockAuditKeeper(ctrl *gomock.Controller) *MockAuditKeeper {
	mock := &MockAuditKeeper{ctrl: ctrl}
	mock.recorder = &MockAuditKeeperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuditKeeper) EXPECT() *MockAuditKeeperMockRecorder {
	return m.recorder
}

// GetCurrentEpochInfo mocks base method.
func (m *MockAuditKeeper) GetCurrentEpochInfo(ctx types1.Context) (uint64, int64, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentEpochInfo", ctx)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(int64)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetCurrentEpochInfo indicates an expected call of GetCurrentEpochInfo.
func (mr *MockAuditKeeperMockRecorder) GetCurrentEpochInfo(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentEpochInfo", reflect.TypeOf((*MockAuditKeeper)(nil).GetCurrentEpochInfo), ctx)
}

// GetReport mocks base method.
func (m *MockAuditKeeper) GetReport(ctx types1.Context, epochID uint64, reporterSupernodeAccount string) (types.EpochReport, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReport", ctx, epochID, reporterSupernodeAccount)
	ret0, _ := ret[0].(types.EpochReport)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetReport indicates an expected call of GetReport.
func (mr *MockAuditKeeperMockRecorder) GetReport(ctx, epochID, reporterSupernodeAccount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReport", reflect.TypeOf((*MockAuditKeeper)(nil).GetReport), ctx, epochID, reporterSupernodeAccount)
}

// MockSlashingKeeper is a mock of SlashingKeeper interface.
type MockSlashingKeeper struct {
	ctrl     *gomock.Controller
	recorder *MockSlashingKeeperMockRecorder
	isgomock struct{}
}

// MockSlashingKeeperMockRecorder is the mock recorder for MockSlashingKeeper.
type MockSlashingKeeperMockRecorder struct {
	mock *MockSlashingKeeper
}

// NewMockSlashingKeeper creates a new mock instance.
func NewMockSlashingKeeper(ctrl *gomock.Controller) *MockSlashingKeeper {
	mock := &MockSlashingKeeper{ctrl: ctrl}
	mock.recorder = &MockSlashingKeeperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSlashingKeeper) EXPECT() *MockSlashingKeeperMockRecorder {
	return m.recorder
}

// IsTombstoned mocks base method.
func (m *MockSlashingKeeper) IsTombstoned(arg0 context.Context, arg1 types1.ConsAddress) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsTombstoned", arg0, arg1)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsTombstoned indicates an expected call of IsTombstoned.
func (mr *MockSlashingKeeperMockRecorder) IsTombstoned(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsTombstoned", reflect.TypeOf((*MockSlashingKeeper)(nil).IsTombstoned), arg0, arg1)
}

// Jail mocks base method.
func (m *MockSlashingKeeper) Jail(arg0 context.Context, arg1 types1.ConsAddress) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Jail", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Jail indicates an expected call of Jail.
func (mr *MockSlashingKeeperMockRecorder) Jail(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Jail", reflect.TypeOf((*MockSlashingKeeper)(nil).Jail), arg0, arg1)
}

// JailUntil mocks base method.
func (m *MockSlashingKeeper) JailUntil(arg0 context.Context, arg1 types1.ConsAddress, arg2 time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JailUntil", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// JailUntil indicates an expected call of JailUntil.
func (mr *MockSlashingKeeperMockRecorder) JailUntil(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JailUntil", reflect.TypeOf((*MockSlashingKeeper)(nil).JailUntil), arg0, arg1, arg2)
}

// Slash mocks base method.
func (m *MockSlashingKeeper) Slash(ctx context.Context, consAddr types1.ConsAddress, fraction math.LegacyDec, power, distributionHeight int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Slash", ctx, consAddr, fraction, power, distributionHeight)
	ret0, _ := ret[0].(error)
	return ret0
}

// Slash indicates an expected call of Slash.
func (mr *MockSlashingKeeperMockRecorder) Slash(ctx, consAddr, fraction, power, distributionHeight any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Slash", reflect.TypeOf((*MockSlashingKeeper)(nil).Slash), ctx, consAddr, fraction, power, distributionHeight)
}

// MockAccountKeeper is a mock of AccountKeeper interface.
type MockAccountKeeper struct {
	ctrl     *gomock.Controller
	recorder *MockAccountKeeperMockRecorder
	isgomock struct{}
}

// MockAccountKeeperMockRecorder is the mock recorder for MockAccountKeeper.
type MockAccountKeeperMockRecorder struct {
	mock *MockAccountKeeper
}

// NewMockAccountKeeper creates a new mock instance.
func NewMockAccountKeeper(ctrl *gomock.Controller) *MockAccountKeeper {
	mock := &MockAccountKeeper{ctrl: ctrl}
	mock.recorder = &MockAccountKeeperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountKeeper) EXPECT() *MockAccountKeeperMockRecorder {
	return m.recorder
}

// GetAccount mocks base method.
func (m *MockAccountKeeper) GetAccount(arg0 context.Context, arg1 types1.AccAddress) types1.AccountI {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccount", arg0, arg1)
	ret0, _ := ret[0].(types1.AccountI)
	return ret0
}

// GetAccount indicates an expected call of GetAccount.
func (mr *MockAccountKeeperMockRecorder) GetAccount(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccount", reflect.TypeOf((*MockAccountKeeper)(nil).GetAccount), arg0, arg1)
}

// GetModuleAccount mocks base method.
func (m *MockAccountKeeper) GetModuleAccount(ctx context.Context, moduleName string) types1.ModuleAccountI {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetModuleAccount", ctx, moduleName)
	ret0, _ := ret[0].(types1.ModuleAccountI)
	return ret0
}

// GetModuleAccount indicates an expected call of GetModuleAccount.
func (mr *MockAccountKeeperMockRecorder) GetModuleAccount(ctx, moduleName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetModuleAccount", reflect.TypeOf((*MockAccountKeeper)(nil).GetModuleAccount), ctx, moduleName)
}

// GetModuleAddress mocks base method.
func (m *MockAccountKeeper) GetModuleAddress(moduleName string) types1.AccAddress {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetModuleAddress", moduleName)
	ret0, _ := ret[0].(types1.AccAddress)
	return ret0
}

// GetModuleAddress indicates an expected call of GetModuleAddress.
func (mr *MockAccountKeeperMockRecorder) GetModuleAddress(moduleName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetModuleAddress", reflect.TypeOf((*MockAccountKeeper)(nil).GetModuleAddress), moduleName)
}

// MockBankKeeper is a mock of BankKeeper interface.
type MockBankKeeper struct {
	ctrl     *gomock.Controller
	recorder *MockBankKeeperMockRecorder
	isgomock struct{}
}

// MockBankKeeperMockRecorder is the mock recorder for MockBankKeeper.
type MockBankKeeperMockRecorder struct {
	mock *MockBankKeeper
}

// NewMockBankKeeper creates a new mock instance.
func NewMockBankKeeper(ctrl *gomock.Controller) *MockBankKeeper {
	mock := &MockBankKeeper{ctrl: ctrl}
	mock.recorder = &MockBankKeeperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBankKeeper) EXPECT() *MockBankKeeperMockRecorder {
	return m.recorder
}

// GetAllBalances mocks base method.
func (m *MockBankKeeper) GetAllBalances(ctx context.Context, addr types1.AccAddress) types1.Coins {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllBalances", ctx, addr)
	ret0, _ := ret[0].(types1.Coins)
	return ret0
}

// GetAllBalances indicates an expected call of GetAllBalances.
func (mr *MockBankKeeperMockRecorder) GetAllBalances(ctx, addr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllBalances", reflect.TypeOf((*MockBankKeeper)(nil).GetAllBalances), ctx, addr)
}

// GetBalance mocks base method.
func (m *MockBankKeeper) GetBalance(ctx context.Context, addr types1.AccAddress, denom string) types1.Coin {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", ctx, addr, denom)
	ret0, _ := ret[0].(types1.Coin)
	return ret0
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockBankKeeperMockRecorder) GetBalance(ctx, addr, denom any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockBankKeeper)(nil).GetBalance), ctx, addr, denom)
}

// SendCoinsFromModuleToAccount mocks base method.
func (m *MockBankKeeper) SendCoinsFromModuleToAccount(ctx context.Context, senderModule string, recipientAddr types1.AccAddress, amt types1.Coins) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendCoinsFromModuleToAccount", ctx, senderModule, recipientAddr, amt)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendCoinsFromModuleToAccount indicates an expected call of SendCoinsFromModuleToAccount.
func (mr *MockBankKeeperMockRecorder) SendCoinsFromModuleToAccount(ctx, senderModule, recipientAddr, amt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendCoinsFromModuleToAccount", reflect.TypeOf((*MockBankKeeper)(nil).SendCoinsFromModuleToAccount), ctx, senderModule, recipientAddr, amt)
}

// SpendableCoins mocks base method.
func (m *MockBankKeeper) SpendableCoins(arg0 context.Context, arg1 types1.AccAddress) types1.Coins {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SpendableCoins", arg0, arg1)
	ret0, _ := ret[0].(types1.Coins)
	return ret0
}

// SpendableCoins indicates an expected call of SpendableCoins.
func (mr *MockBankKeeperMockRecorder) SpendableCoins(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SpendableCoins", reflect.TypeOf((*MockBankKeeper)(nil).SpendableCoins), arg0, arg1)
}

// MockStakingHooks is a mock of StakingHooks interface.
type MockStakingHooks struct {
	ctrl     *gomock.Controller
	recorder *MockStakingHooksMockRecorder
	isgomock struct{}
}

// MockStakingHooksMockRecorder is the mock recorder for MockStakingHooks.
type MockStakingHooksMockRecorder struct {
	mock *MockStakingHooks
}

// NewMockStakingHooks creates a new mock instance.
func NewMockStakingHooks(ctrl *gomock.Controller) *MockStakingHooks {
	mock := &MockStakingHooks{ctrl: ctrl}
	mock.recorder = &MockStakingHooksMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStakingHooks) EXPECT() *MockStakingHooksMockRecorder {
	return m.recorder
}

// AfterDelegationModified mocks base method.
func (m *MockStakingHooks) AfterDelegationModified(ctx context.Context, delAddr types1.AccAddress, valAddr types1.ValAddress) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AfterDelegationModified", ctx, delAddr, valAddr)
	ret0, _ := ret[0].(error)
	return ret0
}

// AfterDelegationModified indicates an expected call of AfterDelegationModified.
func (mr *MockStakingHooksMockRecorder) AfterDelegationModified(ctx, delAddr, valAddr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AfterDelegationModified", reflect.TypeOf((*MockStakingHooks)(nil).AfterDelegationModified), ctx, delAddr, valAddr)
}

// AfterValidatorBeginUnbonding mocks base method.
func (m *MockStakingHooks) AfterValidatorBeginUnbonding(ctx context.Context, consAddr types1.ConsAddress, valAddr types1.ValAddress) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AfterValidatorBeginUnbonding", ctx, consAddr, valAddr)
	ret0, _ := ret[0].(error)
	return ret0
}

// AfterValidatorBeginUnbonding indicates an expected call of AfterValidatorBeginUnbonding.
func (mr *MockStakingHooksMockRecorder) AfterValidatorBeginUnbonding(ctx, consAddr, valAddr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AfterValidatorBeginUnbonding", reflect.TypeOf((*MockStakingHooks)(nil).AfterValidatorBeginUnbonding), ctx, consAddr, valAddr)
}

// AfterValidatorBonded mocks base method.
func (m *MockStakingHooks) AfterValidatorBonded(ctx context.Context, consAddr types1.ConsAddress, valAddr types1.ValAddress) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AfterValidatorBonded", ctx, consAddr, valAddr)
	ret0, _ := ret[0].(error)
	return ret0
}

// AfterValidatorBonded indicates an expected call of AfterValidatorBonded.
func (mr *MockStakingHooksMockRecorder) AfterValidatorBonded(ctx, consAddr, valAddr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AfterValidatorBonded", reflect.TypeOf((*MockStakingHooks)(nil).AfterValidatorBonded), ctx, consAddr, valAddr)
}

// AfterValidatorCreated mocks base method.
func (m *MockStakingHooks) AfterValidatorCreated(ctx context.Context, valAddr types1.ValAddress) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AfterValidatorCreated", ctx, valAddr)
	ret0, _ := ret[0].(error)
	return ret0
}

// AfterValidatorCreated indicates an expected call of AfterValidatorCreated.
func (mr *MockStakingHooksMockRecorder) AfterValidatorCreated(ctx, valAddr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AfterValidatorCreated", reflect.TypeOf((*MockStakingHooks)(nil).AfterValidatorCreated), ctx, valAddr)
}

// AfterValidatorRemoved mocks base method.
func (m *MockStakingHooks) AfterValidatorRemoved(ctx context.Context, consAddr types1.ConsAddress, valAddr types1.ValAddress) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AfterValidatorRemoved", ctx, consAddr, valAddr)
	ret0, _ := ret[0].(error)
	return ret0
}

// AfterValidatorRemoved indicates an expected call of AfterValidatorRemoved.
func (mr *MockStakingHooksMockRecorder) AfterValidatorRemoved(ctx, consAddr, valAddr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AfterValidatorRemoved", reflect.TypeOf((*MockStakingHooks)(nil).AfterValidatorRemoved), ctx, consAddr, valAddr)
}

// BeforeDelegationCreated mocks base method.
func (m *MockStakingHooks) BeforeDelegationCreated(ctx context.Context, delAddr types1.AccAddress, valAddr types1.ValAddress) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeforeDelegationCreated", ctx, delAddr, valAddr)
	ret0, _ := ret[0].(error)
	return ret0
}

// BeforeDelegationCreated indicates an expected call of BeforeDelegationCreated.
func (mr *MockStakingHooksMockRecorder) BeforeDelegationCreated(ctx, delAddr, valAddr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeforeDelegationCreated", reflect.TypeOf((*MockStakingHooks)(nil).BeforeDelegationCreated), ctx, delAddr, valAddr)
}

// BeforeDelegationRemoved mocks base method.
func (m *MockStakingHooks) BeforeDelegationRemoved(ctx context.Context, delAddr types1.AccAddress, valAddr types1.ValAddress) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeforeDelegationRemoved", ctx, delAddr, valAddr)
	ret0, _ := ret[0].(error)
	return ret0
}

// BeforeDelegationRemoved indicates an expected call of BeforeDelegationRemoved.
func (mr *MockStakingHooksMockRecorder) BeforeDelegationRemoved(ctx, delAddr, valAddr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeforeDelegationRemoved", reflect.TypeOf((*MockStakingHooks)(nil).BeforeDelegationRemoved), ctx, delAddr, valAddr)
}

// BeforeDelegationSharesModified mocks base method.
func (m *MockStakingHooks) BeforeDelegationSharesModified(ctx context.Context, delAddr types1.AccAddress, valAddr types1.ValAddress) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeforeDelegationSharesModified", ctx, delAddr, valAddr)
	ret0, _ := ret[0].(error)
	return ret0
}

// BeforeDelegationSharesModified indicates an expected call of BeforeDelegationSharesModified.
func (mr *MockStakingHooksMockRecorder) BeforeDelegationSharesModified(ctx, delAddr, valAddr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeforeDelegationSharesModified", reflect.TypeOf((*MockStakingHooks)(nil).BeforeDelegationSharesModified), ctx, delAddr, valAddr)
}

// BeforeValidatorModified mocks base method.
func (m *MockStakingHooks) BeforeValidatorModified(ctx context.Context, valAddr types1.ValAddress) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeforeValidatorModified", ctx, valAddr)
	ret0, _ := ret[0].(error)
	return ret0
}

// BeforeValidatorModified indicates an expected call of BeforeValidatorModified.
func (mr *MockStakingHooksMockRecorder) BeforeValidatorModified(ctx, valAddr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeforeValidatorModified", reflect.TypeOf((*MockStakingHooks)(nil).BeforeValidatorModified), ctx, valAddr)
}

// BeforeValidatorSlashed mocks base method.
func (m *MockStakingHooks) BeforeValidatorSlashed(ctx context.Context, valAddr types1.ValAddress, fraction math.LegacyDec) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeforeValidatorSlashed", ctx, valAddr, fraction)
	ret0, _ := ret[0].(error)
	return ret0
}

// BeforeValidatorSlashed indicates an expected call of BeforeValidatorSlashed.
func (mr *MockStakingHooksMockRecorder) BeforeValidatorSlashed(ctx, valAddr, fraction any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeforeValidatorSlashed", reflect.TypeOf((*MockStakingHooks)(nil).BeforeValidatorSlashed), ctx, valAddr, fraction)
}
