// Copyright (c) 2024-2025 The Lumera developers
//

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/cosmos/cosmos-sdk/crypto/keyring (interfaces: Keyring)
//
// Generated by this command:
//
//	mockgen -copyright_file=../mock_header.txt -destination=../mocks/keyring_mocks.go -package=testutilsmocks github.com/cosmos/cosmos-sdk/crypto/keyring Keyring
//

// Package testutilsmocks is a generated GoMock package.
package testutilsmocks

import (
	reflect "reflect"

	keyring "github.com/cosmos/cosmos-sdk/crypto/keyring"
	types "github.com/cosmos/cosmos-sdk/crypto/types"
	types0 "github.com/cosmos/cosmos-sdk/types"
	signing "github.com/cosmos/cosmos-sdk/types/tx/signing"
	gomock "go.uber.org/mock/gomock"
)

// MockKeyring is a mock of Keyring interface.
type MockKeyring struct {
	ctrl     *gomock.Controller
	recorder *MockKeyringMockRecorder
	isgomock struct{}
}

// MockKeyringMockRecorder is the mock recorder for MockKeyring.
type MockKeyringMockRecorder struct {
	mock *MockKeyring
}

// NewMockKeyring creates a new mock instance.
func NewMockKeyring(ctrl *gomock.Controller) *MockKeyring {
	mock := &MockKeyring{ctrl: ctrl}
	mock.recorder = &MockKeyringMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKeyring) EXPECT() *MockKeyringMockRecorder {
	return m.recorder
}

// Backend mocks base method.
func (m *MockKeyring) Backend() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Backend")
	ret0, _ := ret[0].(string)
	return ret0
}

// Backend indicates an expected call of Backend.
func (mr *MockKeyringMockRecorder) Backend() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Backend", reflect.TypeOf((*MockKeyring)(nil).Backend))
}

// Delete mocks base method.
func (m *MockKeyring) Delete(uid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", uid)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockKeyringMockRecorder) Delete(uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockKeyring)(nil).Delete), uid)
}

// DeleteByAddress mocks base method.
func (m *MockKeyring) DeleteByAddress(address types0.Address) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByAddress", address)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByAddress indicates an expected call of DeleteByAddress.
func (mr *MockKeyringMockRecorder) DeleteByAddress(address any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByAddress", reflect.TypeOf((*MockKeyring)(nil).DeleteByAddress), address)
}

// ExportPrivKeyArmor mocks base method.
func (m *MockKeyring) ExportPrivKeyArmor(uid, encryptPassphrase string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExportPrivKeyArmor", uid, encryptPassphrase)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExportPrivKeyArmor indicates an expected call of ExportPrivKeyArmor.
func (mr *MockKeyringMockRecorder) ExportPrivKeyArmor(uid, encryptPassphrase any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExportPrivKeyArmor", reflect.TypeOf((*MockKeyring)(nil).ExportPrivKeyArmor), uid, encryptPassphrase)
}

// ExportPrivKeyArmorByAddress mocks base method.
func (m *MockKeyring) ExportPrivKeyArmorByAddress(address types0.Address, encryptPassphrase string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExportPrivKeyArmorByAddress", address, encryptPassphrase)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExportPrivKeyArmorByAddress indicates an expected call of ExportPrivKeyArmorByAddress.
func (mr *MockKeyringMockRecorder) ExportPrivKeyArmorByAddress(address, encryptPassphrase any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExportPrivKeyArmorByAddress", reflect.TypeOf((*MockKeyring)(nil).ExportPrivKeyArmorByAddress), address, encryptPassphrase)
}

// ExportPubKeyArmor mocks base method.
func (m *MockKeyring) ExportPubKeyArmor(uid string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExportPubKeyArmor", uid)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExportPubKeyArmor indicates an expected call of ExportPubKeyArmor.
func (mr *MockKeyringMockRecorder) ExportPubKeyArmor(uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExportPubKeyArmor", reflect.TypeOf((*MockKeyring)(nil).ExportPubKeyArmor), uid)
}

// ExportPubKeyArmorByAddress mocks base method.
func (m *MockKeyring) ExportPubKeyArmorByAddress(address types0.Address) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExportPubKeyArmorByAddress", address)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExportPubKeyArmorByAddress indicates an expected call of ExportPubKeyArmorByAddress.
func (mr *MockKeyringMockRecorder) ExportPubKeyArmorByAddress(address any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExportPubKeyArmorByAddress", reflect.TypeOf((*MockKeyring)(nil).ExportPubKeyArmorByAddress), address)
}

// ImportPrivKey mocks base method.
func (m *MockKeyring) ImportPrivKey(uid, armor, passphrase string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImportPrivKey", uid, armor, passphrase)
	ret0, _ := ret[0].(error)
	return ret0
}

// ImportPrivKey indicates an expected call of ImportPrivKey.
func (mr *MockKeyringMockRecorder) ImportPrivKey(uid, armor, passphrase any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImportPrivKey", reflect.TypeOf((*MockKeyring)(nil).ImportPrivKey), uid, armor, passphrase)
}

// ImportPrivKeyHex mocks base method.
func (m *MockKeyring) ImportPrivKeyHex(uid, privKey, algoStr string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImportPrivKeyHex", uid, privKey, algoStr)
	ret0, _ := ret[0].(error)
	return ret0
}

// ImportPrivKeyHex indicates an expected call of ImportPrivKeyHex.
func (mr *MockKeyringMockRecorder) ImportPrivKeyHex(uid, privKey, algoStr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImportPrivKeyHex", reflect.TypeOf((*MockKeyring)(nil).ImportPrivKeyHex), uid, privKey, algoStr)
}

// ImportPubKey mocks base method.
func (m *MockKeyring) ImportPubKey(uid, armor string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImportPubKey", uid, armor)
	ret0, _ := ret[0].(error)
	return ret0
}

// ImportPubKey indicates an expected call of ImportPubKey.
func (mr *MockKeyringMockRecorder) ImportPubKey(uid, armor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImportPubKey", reflect.TypeOf((*MockKeyring)(nil).ImportPubKey), uid, armor)
}

// Key mocks base method.
func (m *MockKeyring) Key(uid string) (*keyring.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Key", uid)
	ret0, _ := ret[0].(*keyring.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Key indicates an expected call of Key.
func (mr *MockKeyringMockRecorder) Key(uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Key", reflect.TypeOf((*MockKeyring)(nil).Key), uid)
}

// KeyByAddress mocks base method.
func (m *MockKeyring) KeyByAddress(address types0.Address) (*keyring.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "KeyByAddress", address)
	ret0, _ := ret[0].(*keyring.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// KeyByAddress indicates an expected call of KeyByAddress.
func (mr *MockKeyringMockRecorder) KeyByAddress(address any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "KeyByAddress", reflect.TypeOf((*MockKeyring)(nil).KeyByAddress), address)
}

// List mocks base method.
func (m *MockKeyring) List() ([]*keyring.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].([]*keyring.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockKeyringMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockKeyring)(nil).List))
}

// MigrateAll mocks base method.
func (m *MockKeyring) MigrateAll() ([]*keyring.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MigrateAll")
	ret0, _ := ret[0].([]*keyring.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MigrateAll indicates an expected call of MigrateAll.
func (mr *MockKeyringMockRecorder) MigrateAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MigrateAll", reflect.TypeOf((*MockKeyring)(nil).MigrateAll))
}

// NewAccount mocks base method.
func (m *MockKeyring) NewAccount(uid, mnemonic, bip39Passphrase, hdPath string, algo keyring.SignatureAlgo) (*keyring.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewAccount", uid, mnemonic, bip39Passphrase, hdPath, algo)
	ret0, _ := ret[0].(*keyring.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewAccount indicates an expected call of NewAccount.
func (mr *MockKeyringMockRecorder) NewAccount(uid, mnemonic, bip39Passphrase, hdPath, algo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewAccount", reflect.TypeOf((*MockKeyring)(nil).NewAccount), uid, mnemonic, bip39Passphrase, hdPath, algo)
}

// NewMnemonic mocks base method.
func (m *MockKeyring) NewMnemonic(uid string, language keyring.Language, hdPath, bip39Passphrase string, algo keyring.SignatureAlgo) (*keyring.Record, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewMnemonic", uid, language, hdPath, bip39Passphrase, algo)
	ret0, _ := ret[0].(*keyring.Record)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// NewMnemonic indicates an expected call of NewMnemonic.
func (mr *MockKeyringMockRecorder) NewMnemonic(uid, language, hdPath, bip39Passphrase, algo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewMnemonic", reflect.TypeOf((*MockKeyring)(nil).NewMnemonic), uid, language, hdPath, bip39Passphrase, algo)
}

// Rename mocks base method.
func (m *MockKeyring) Rename(from, to string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rename", from, to)
	ret0, _ := ret[0].(error)
	return ret0
}

// Rename indicates an expected call of Rename.
func (mr *MockKeyringMockRecorder) Rename(from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rename", reflect.TypeOf((*MockKeyring)(nil).Rename), from, to)
}

// SaveLedgerKey mocks base method.
func (m *MockKeyring) SaveLedgerKey(uid string, algo keyring.SignatureAlgo, hrp string, coinType, account, index uint32) (*keyring.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveLedgerKey", uid, algo, hrp, coinType, account, index)
	ret0, _ := ret[0].(*keyring.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveLedgerKey indicates an expected call of SaveLedgerKey.
func (mr *MockKeyringMockRecorder) SaveLedgerKey(uid, algo, hrp, coinType, account, index any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveLedgerKey", reflect.TypeOf((*MockKeyring)(nil).SaveLedgerKey), uid, algo, hrp, coinType, account, index)
}

// SaveMultisig mocks base method.
func (m *MockKeyring) SaveMultisig(uid string, pubkey types.PubKey) (*keyring.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveMultisig", uid, pubkey)
	ret0, _ := ret[0].(*keyring.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveMultisig indicates an expected call of SaveMultisig.
func (mr *MockKeyringMockRecorder) SaveMultisig(uid, pubkey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveMultisig", reflect.TypeOf((*MockKeyring)(nil).SaveMultisig), uid, pubkey)
}

// SaveOfflineKey mocks base method.
func (m *MockKeyring) SaveOfflineKey(uid string, pubkey types.PubKey) (*keyring.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveOfflineKey", uid, pubkey)
	ret0, _ := ret[0].(*keyring.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveOfflineKey indicates an expected call of SaveOfflineKey.
func (mr *MockKeyringMockRecorder) SaveOfflineKey(uid, pubkey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveOfflineKey", reflect.TypeOf((*MockKeyring)(nil).SaveOfflineKey), uid, pubkey)
}

// Sign mocks base method.
func (m *MockKeyring) Sign(uid string, msg []byte, signMode signing.SignMode) ([]byte, types.PubKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sign", uid, msg, signMode)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(types.PubKey)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Sign indicates an expected call of Sign.
func (mr *MockKeyringMockRecorder) Sign(uid, msg, signMode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sign", reflect.TypeOf((*MockKeyring)(nil).Sign), uid, msg, signMode)
}

// SignByAddress mocks base method.
func (m *MockKeyring) SignByAddress(address types0.Address, msg []byte, signMode signing.SignMode) ([]byte, types.PubKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignByAddress", address, msg, signMode)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(types.PubKey)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SignByAddress indicates an expected call of SignByAddress.
func (mr *MockKeyringMockRecorder) SignByAddress(address, msg, signMode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignByAddress", reflect.TypeOf((*MockKeyring)(nil).SignByAddress), address, msg, signMode)
}

// SupportedAlgorithms mocks base method.
func (m *MockKeyring) SupportedAlgorithms() (keyring.SigningAlgoList, keyring.SigningAlgoList) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SupportedAlgorithms")
	ret0, _ := ret[0].(keyring.SigningAlgoList)
	ret1, _ := ret[1].(keyring.SigningAlgoList)
	return ret0, ret1
}

// SupportedAlgorithms indicates an expected call of SupportedAlgorithms.
func (mr *MockKeyringMockRecorder) SupportedAlgorithms() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SupportedAlgorithms", reflect.TypeOf((*MockKeyring)(nil).SupportedAlgorithms))
}
