name: lint

on:
  push:
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.gitignore'
  pull_request:
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.gitignore'
  workflow_call:

permissions:
  contents: read

jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.1

      - name: Set up Go
        uses: ./.github/actions/setup-go

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v9.2.0
        with:
          version: v2.1.6
          args: --timeout=5m
