name: tests

on:
  push:
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.gitignore'

jobs:
  unit-tests:
    name: unit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.2'

      - name: Copy claims.csv to home directory
        run: cp claims.csv $HOME/

      - name: Install Ignite CLI
        run: |
          curl https://get.ignite.com/cli! | bash
        env:
          IGNITE_CLI_NO_ANALYTICS: 1

      - name: Install dependencies
        run: go mod download

      - name: Run unit tests
        run: go test ./... -v

  integration-tests:
    name: integration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.2'

      - name: Copy claims.csv to home directory
        run: cp claims.csv $HOME/

      - name: Install Ignite CLI
        run: |
          curl https://get.ignite.com/cli! | bash
        env:
          IGNITE_CLI_NO_ANALYTICS: 1

      - name: Install dependencies
        run: go mod download

      - name: Run integration tests
        run: go test -tags=integration ./tests/integration/... -v

  system-tests:
    name: system
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git Safe Directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Get Go version from toolchain
        id: go-version
        run: |
          TOOLCHAIN_VERSION=$(grep -E '^toolchain go[0-9]+\.[0-9]+(\.[0-9]+)?$' go.mod | cut -d ' ' -f 2 | sed 's/^go//')
          if [ -n "$TOOLCHAIN_VERSION" ]; then
            echo "version=$TOOLCHAIN_VERSION" >> "$GITHUB_OUTPUT"
          else
            GO_VERSION=$(grep -E '^go [0-9]+\.[0-9]+(\.[0-9]+)?$' go.mod | cut -d ' ' -f 2)
            echo "version=$GO_VERSION" >> "$GITHUB_OUTPUT"
          fi

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ steps.go-version.outputs.version }}
          cache: true

      - name: Install Specific Ignite CLI Version
        run: |
          IGNITE_VERSION="v28.6.0"
          ARCH="linux_amd64"

          curl -L "https://github.com/ignite/cli/releases/download/${IGNITE_VERSION}/ignite_${IGNITE_VERSION#v}_checksums.txt" -o checksums.txt
          EXPECTED_CHECKSUM=$(grep "ignite_${IGNITE_VERSION#v}_${ARCH}.tar.gz" checksums.txt | awk '{print $1}')

          curl -L "https://github.com/ignite/cli/releases/download/${IGNITE_VERSION}/ignite_${IGNITE_VERSION#v}_${ARCH}.tar.gz" -o ignite.tar.gz
          ACTUAL_CHECKSUM=$(sha256sum ignite.tar.gz | awk '{print $1}')
          if [ "$ACTUAL_CHECKSUM" != "$EXPECTED_CHECKSUM" ]; then
            echo "Error: Checksum mismatch!"
            exit 1
          fi

          tar -xzf ignite.tar.gz
          chmod +x ignite
          # Ignite CLI is now available at ./ignite

      - name: Build Chain 
        
        run: |
          ./ignite chain build -y -t linux:amd64
        env:
          DO_NOT_TRACK: 1
          GOFLAGS: "-buildvcs=false"

      - name: Prepare System Tests
        run: |
          cd tests/systemtests
          go mod tidy

      - name: Run System Tests
        run: |
          cd tests/systemtests
          go test -tags=system_test -v .

  simulation-tests:
    name: simulation
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.2'

      - name: Copy claims.csv to home directory
        run: cp claims.csv $HOME/

      - name: Install Ignite CLI
        run: |
          curl https://get.ignite.com/cli! | bash
        env:
          IGNITE_CLI_NO_ANALYTICS: 1

      - name: Install dependencies
        run: go mod download

      - name: Run simulation tests
        env:
          GOMAXPROCS: 2
          IGNITE_TELEMETRY_CONSENT: "no"
        run: |
          go test -v -benchmem -run=^$ -bench ^BenchmarkSimulation -cpuprofile cpu.out ./app -Commit=true