FROM debian:bookworm-slim


ARG APP_VERSION=1.0.0
ARG APP_NAME=lumera-docker
ARG SCRIPTS_SRC_DIR=scripts
ARG SCRIPTS_DEST_DIR=/root/scripts

LABEL Name="${APP_NAME}" \
      Version="${APP_VERSION}"

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    jq \
    bash \
    sed \
    libwebp-dev \
    ca-certificates \
    procps \
    crudini \
    net-tools \
    iputils-ping \
    lnav \
    mc \
    && rm -rf /var/lib/apt/lists/*

# Update libraries cache & create directories
RUN ldconfig && mkdir -p ${SCRIPTS_DEST_DIR} /root/.lumerad

# Copy scripts with correct paths
COPY --chmod=0755 \
    ${SCRIPTS_SRC_DIR}/start.sh \
    ${SCRIPTS_SRC_DIR}/validator-setup.sh \
    ${SCRIPTS_SRC_DIR}/supernode-setup.sh \
    ${SCRIPTS_SRC_DIR}/network-maker-setup.sh \
    ${SCRIPTS_DEST_DIR}/

# Expose necessary ports
EXPOSE 26656 26657 1317 9090 4444 8002

# Set working directory
WORKDIR /root

ENTRYPOINT ["/bin/bash", "/root/scripts/start.sh"]